### ISSUE TITLE
appimagelauncher remove not found

### ISSUE THREAD

**Issue by LyzardKing** [TheAssassin/AppImageLauncher#107]
Hi.
I'm running the latest version of bionic appimagelauncher,
on kde neon (not sure if it makes any difference, probably not)
If I integrate an appimage it works, but does not show any icon, on the file and the menu.
If I try to uninstall I get the following error:
`Could not find the program '/usr/lib/appimagelauncher/remove'`

**Comment by LyzardKing** [comment]
No problem!
That version works regarding the removal.
The icons are still not shown..

**Comment by TheAssassin** [comment]
Icons not being shown on Plasma 5 is a known bug, but in Plasma. They have some caching for such data which you cannot update using some tools (unlike the GNOME icon cache used in many other DEs). Are they shown after logging out and in? If yes, then it's a Plasma 5 issue, otherwise it might be a bug in libappimage.

**Comment by LyzardKing** [comment]
It does work after a logout!
Perfect. Thanks.
I'll close this issue then!

**Comment by TheAssassin** [comment]
Let's keep it open to remind me of this (second) issue with the latest builds.
