### ISSUE TITLE
Add option to disable "move into integration directory" step

### ISSUE THREAD

**Issue by 2635599** [TheAssassin/AppImageLauncher#111]
thought when appimage launcher was mentioned in the below linked thread that it would be a great addition for making appimages easier to use, but was surprised to find out after clicking integrate and run appimage launcher removes the actual appimage. that should never happen. i either need a way to remove your program or a way to keep it from deleting the appimage file after it integrates it into the systemhanks

 https://forums.linuxmint.com/viewtopic.php?f=47&t=284214&p=1573456#p1573456

**Comment by TheAssassin** [comment]
First of all, thanks to "MrGrimm" for this very nice quote:

> [...] this "appimage launcher" IS a true piece of shit.

The files aren't deleted, they're moved to `~/Applications`. The integration dialog explicitly states that the file will be moved to `<insert home dir here>/Applications`. We have _never_ experienced this to fail (actually, there's an error check for this, and the file would remain in the original location).

**Comment by 2635599** [comment]
**First** of all, **NOTHING** wrong with my statement. **DEAL WITH IT**. **SECOND** right out of the gate we should have been given the option of allowing appimage launcher to move the files or to leave them where they are found.

**Comment by TheAssassin** [comment]
You should calm down, @2635599. I just wanted to save this quote for the future. You should be proud.

Since you seem to appreciate a more aggressive language: *You failed* to read the README (https://github.com/TheAssassin/AppImageLauncher#appimage-desktop-integration), and then started to rage about the behavior. Decisions in that regard were made during the initial design phase, and many users do like it. Doesn't mean everyone does, it depends on your preferences of course.

Interpreting the second half of your statement, your issue title is wrong, the files were just moved but were not deleted.

If you want to continue collaborating on making this application better, we could turn this issue into a feature request to introduce a feature/setting/... to turn off this while preserving the rest of the features (integration into the menu, creating updating and removal context menu entries, ...). Suggestions welcome!

**Comment by 2635599** [comment]
two questions. i went a head and installed kde, logged in, looked around, ran a few of my programs already installed, logged out and back into cinnamon, notice a few broken appimages, ones i ran while in kde. would i be correct in assuming that if i had installed them using your launcher i would of avoided this? second is there any reason i can recreate the applications folder on my backup drive and link to it so when i run your launcher it saves the appimages there but thinks they are in the default location?

**Comment by TheAssassin** [comment]
You can already change the destination integration directory (it's not very well documented, sorry for that...) by editing the AppImageLauncher config file:

```
~> cat ~/.config/appimagelauncher.cfg 
[AppImageLauncher]
# destination = ~/Applications
[...]
```

Just uncomment `destination` and set it to a path you like.

Regarding your first question, it depends what you understand as "broken". I'm not sure what you mean there. AppImageLauncher only takes care of making `$AppImage` executable, moving it into the so-called integration destination directory and creating the entries in the launcher. It uses distribution/desktop environment agnostic standards for this.

By the way, AppImageLauncher ships with a little daemon that will _automatically_ integrate AppImages moved into said destination directory. So, if your workflow is to move the files around manually, that might be more suitable for you. We plan to allow for enabling only this daemon and disabling the UI, but due to limited time and the amount of testing involved, this hasn't been realized yet.

**Comment by 2635599** [comment]
o.k. i figured i'd need to clairify, sorry. now for wgat i was getting at is if i rightclick the cinnamon desktop or in a folder to create a launcher it works great, but if i logout, go into kde use it it's broken when when i go back to cinnamon. what i'm thinking since your launcher is treating a appimage as a installable file using a launcher created by your app should not break and become unusable switching between desktops. 

as for the destination something like this, yes?

`
~> cat ~/.config/appimagelauncher.cfg 
[AppImageLauncher]
# destination = **home/CombinedPartitions/MrGrimm's Docs/Backups/Mint Backups/Applications**
[...]
`

**Comment by TheAssassin** [comment]
Please uncomment the line by removing the leading `# `, then it should work, yes. Haven't tested it in a while, so if there's issues, please create a new one.

Regarding your question re. desktop integration, the same code is used on all desktops, so I'm not sure what's going on there. KDE is known to be a bit annoying re. icons in menus for new entries, as they cache this stuff and that cache can't be updated by tools. Can you describe what you mean with "it breaks"? Is the entry gone? Is an icon missing? Perhaps I can ask for more information then, if I know what to look into.

**Comment by 2635599** [comment]
o.k. so

```
~> cat ~/.config/appimagelauncher.cfg 
[AppImageLauncher]
destination = ~/home/CombinedPartitions/MrGrimm's Docs/Backups/Mint Backups/Applications
[...]
```
wasn't sure about the ~

**Comment by TheAssassin** [comment]
Err... now that you mention it... that's an alias for your home directory (as in `~` -> `/home/<username>`). You don't need it. Sorry for the confusion. Please try

```
[AppImageLauncher]
destination = /home/CombinedPartitions/MrGrimm's Docs/Backups/Mint Backups/Applications

**Comment by 2635599** [comment]
that's what i thought. it's ok cause after i made that last post i realize i'll see the layout when i open the file anyway.

**Comment by probonopd** [comment]
I can feel with you @2635599. Do you like [appimaged](https://github.com/AppImage/appimaged) better? it never asks any questions, and it never moves anything anywhere.

**Comment by 2635599** [comment]
while that looks good i think i'm better off with appimage launcher simply because per the above posts with a minor edit i don't have to have the appimages on the os drive.

**Comment by probonopd** [comment]
WIth `appimaged` you can have AppImages on different drives, too ;-)

**Comment by 2635599** [comment]
@TheAssassin i don't know where you are on this, or if you've even moved on this but what i'd actually prefer is the option to leave a copy of the appimage in the original location while a copy is place in the one directory.

**Comment by 2635599** [comment]
@probonopd how does one contact peeps without having to hijack a thread like i'm doing with my own thread now? i'd like more info on your appimaged project. thanks

**Comment by TheAssassin** [comment]
@2635599 but why have two copies of the AppImage on the computer? That seems a bit redundant. What's the user story behind that?

**Comment by 2635599** [comment]
not if the os dribe dies for some reason. then you at least have a copy on a secondary drive. i do not keep anything on my os drive that i can't afford to lose. or if it's easier like in windows have your program open the containing folder aso one can copy the appimage and place that copy in the folder they had the one in.

**Comment by probonopd** [comment]
I also have more than two copies of everything on multiple drives, including AppImages.
