### ISSUE TITLE
Allow "installation" for "All users"

### ISSUE THREAD

**Issue by Nabellaleen** [TheAssassin/AppImageLauncher#135]
Hi,

Is it possible to "install" the AppImage for "All Users" ?

I've found the `~/.config/appimagelauncher.cfg` config file and it's `destination` option, which allow to move the AppImage to `/opt/Applications` for example, but I didn't found an option to choose where to add the `.desktop` file, to be able to add it to `/usr/locale/share/Applications` for a "multi-user" behaviour

Is there such an option ?

Or do you think it's possible to add a feature allowing to choose between "current-user-only" and "all-users" when opening an AppImage ?

**Comment by TheAssassin** [comment]
AppImages are more of a per-user thing. But I'm open to adding a "global install" option where we ask for a root password to move the AppImages into a global directory and integrate them.

**Comment by TheAssassin** [comment]
We need to implement support for `/Applications` in appimagelauncherd first (#154).

**Comment by TheAssassin** [comment]
PR #235 implements all we need to work on this in the future. For now it only implements monitoring `/Applications`. That means that any AppImage placed in that directory is visible to *any* user on the entire system, as long as they have appimagelauncherd activated.

If we manage to find a suitable UX for "global installation", we might extend the integration dialog so that it offers a global installation as well. I'm not sure whether we need this though, nor how to realize it while maintaining the dialog's simplicity. Therefore staging as low prio for now.

**Comment by TheAssassin** [comment]
Oh, by the way, `/Applications` is, to us AppImage devs, the obvious system-wide directory to store AppImages in. So far AppImageLauncher doesn't have a system-wide configuration file that might allow admins to add additional directories.

Whoever thinks this feature is important, please feel free to open another issue.

Regarding this issue, I just changed my mind. This issue is specifically about creating a way to "install" AppImages for "all users", which #235 perfectly provides. In order to keep things simple and manageable, I'll close this issue therefore when #235 is merged. If you want a "install system wide" option in AppImageLauncher's interface, please open a new issue.
