### ISSUE TITLE
Do releases with timestamp "yyyymmdd-hhmm" in file releasenames?

### ISSUE THREAD

**Issue by star-buck** [TheAssassin/AppImageLauncher#14]
this way it could be spotted easily which is the newer ones and reported back against.

**Comment by star-buck** [comment]
When downloading files and storing them, one cannot easily spot which is
the latest one from the filename. The last commit reference is in my
usecase a meaningless info to put in the filename.

**Comment by TheAssassin** [comment]
So, in your case, you only need to know whether the version you download is newer than another one?

For this purpose, the Travis build number is inserted in the filenames:
  - `appimagelauncher_1-alpha-git16e5f34.travis64_amd64.deb` (actually, the `.` should be tilde, but somehow GitHub doesn't like that)
  - `AppImageLauncher-64-16e5f34-x86_64.AppImage` (the `travis` prefix is missing, therefore this number is not really as useful as in the Debian package's filename)

Due to the position of the build number, the AppImages should be sorted correctly. I think I will swap those two parts in the Debian package name therefore. In any case, by comparing the build numbers, it's possible to distinguish between newer and older builds.

I doubt that a "build date" is permitted in Debian packages, but what I've seen before is that, instead of a git commit ID, the date of the commit has been used in the form of `gitYYYYMMDD`. This might be an alternative. We should check the Debian guidelines on version numbers, those guys know what they're doing, and apply the final solution to all released packages.

**Comment by shoogle** [comment]
Debian [permits build dates](https://www.debian.org/doc/debian-policy/#version-numbers-based-on-dates):

> the date-based portion of any upstream version number should be given in a way that sorts correctly: four-digit year first, followed by a two-digit numeric month, followed by a two-digit numeric date, possibly with punctuation between the components.

However [semantic versioning](https://semver.org/) (`MAJOR.MINOR.PATCH`) is encouraged for stable releases (as opposed to development builds).

The most important thing is that versions need to be increasing so that they sort into the right order. This means you need to be careful if you decide to switch from dated versioning now to semantic versioning later.

The best thing to do is have separate packages for stable and unstable builds. Call the stable builds `AppImageLauncher` and use semantic versioning (starting with version `0.1.0` if you are not ready for a version 1 yet). Send these packages to Debian.

Call the unstable builds `AppImageLauncher-continuous` or `AppImageLauncher-nightly` and use dated versioning like `YYYYMMDDhhmm` (don't separate the fields with `-` as some packaging formats don't allow this character). Don't send these to Debian, just put them in a [PPA](https://launchpad.net/~mscore-ubuntu/+archive/ubuntu/mscore-nightly) (Launchpad can do daily [code imports](https://help.launchpad.net/Code/Imports) from GitHub and [automatic DEB builds into a PPA](https://help.launchpad.net/Packaging/SourceBuilds/GettingStarted)) or leave them on your GitHub releases page.
