### ISSUE TITLE
Allow exclusion for files having their own installation methods

### ISSUE THREAD

**Issue by faizalluthfi** [TheAssassin/AppImageLauncher#144]
Some appimage binaries have their own installation methods, for example: electron applications built with electron builder. So it will be useful to exclude them from destop integration confirmation if user decided to exclude them.

**Comment by TheAssassin** [comment]
Thanks for your detailed proposal.

The AppImage project highly discourage any sort of "bundled desktop integration" nowadays, since, despite seeming useful, this creates a lot of problems: There's no proper "removal" of that data any more, it's a very inconsistent look and feel, and might conflict with other solutions. It's better, easier to manage and also less bloaty to install some sort of integration system wide.

Electron particularly doesn't use most of our tools, but they implemented their own. The electron-builder maintainer decided to include the deprecated desktop integration script. Nothing we have control about. 

Luckily, the AppImage specification requires such bundled scripts to remain silent and let system-wide solutions precede. AppImageLauncher, being such a system wide solution, instructs the AppImages to _not_ show these dialogs on purpose.

Even if you disagree with the stance regarding the precedence of system-wide installed solutions, here's another technical reason why to implement it this way: it's immensely hard to predict whether an AppImage ships with some sort of desktop integration thingy. It's however much easier for those scripts to recognize whether there's something installed on the system.

Your proposal is an anti-feature, there is nothing to "fix" here. Therefore closing this as *wontfix*.

**Comment by faizalluthfi** [comment]
Thanks, I understand now. In my case, electron application in my computer already created it's own entry in desktop applications launcher (in linux, it is *.desktop file) before appimagelauncher install, but when I open it from the apps launcher, appimagelauncher confirmed me to integrate electron application with the desktop.

To stop that integration confirmation, I just have to:
- remove the application *.desktop file created by electron builder manually,
- then I double click it again,
- then only appimagelauncher confirms me once to integrate application into desktop and the application does not confirm me again to use it's own integration implementation.

**Comment by TheAssassin** [comment]
We are aware of these issues, and these are exactly why we don't want people to ship their own nonstandard integration solutions. Glad you fixed it.
