### ISSUE TITLE
Make a SystemImageKit ExtensionImage

### ISSUE THREAD

**Issue by probonopd** [TheAssassin/AppImageLauncher#160]
It would be useful for testing if we had a Make an ExtensionImage, similar to https://github.com/probonopd/SystemImageKit/blob/master/boot/bin/generate-appimaged-extension

**Comment by TheAssassin** [comment]
This is nothing AppImageLauncher as a project has to do, but SystemImageKit.

**Comment by probonopd** [comment]
Yes, I'd welcome a PR to SystemImageKit.

**Comment by TheAssassin** [comment]
Then maybe open an issue there and ask your contributors?

Not an AIL issue. Closing as wontfix.

**Comment by probonopd** [comment]
Opened an issue there. My line of thinking is: If AppImageLauncher is inteded as a replacement of appimaged, it must do what appiamged does today, including how other projects like SystemImageKit use it. Unless it does that, it cannot be a replacement for me. (In general: if someone intends to replace my software $FOO with software $BAR, that someone should make sure that $BAR at least does what $FOO did, ideally as a drop-in replacement that does not require one to make changes in usage patterns.)

**Comment by TheAssassin** [comment]
You're not the center of the Linux world, though. AppImageLauncher works great as it is, can be installed and used nearly everywhere, nobody but you really uses SystemImageKit at all so I don't see why I or anyone else should even think about investing time to ship it there. That's not my problem. You always mention your lack of time, but please understand that I and many others also don't have time. Asking us to worry about _your_ personal third-party projects none of us uses because you don't get to fixing them is pretty outrageous IMO.

This is by the way not a replacement of appimaged, it's an alternative. I keep explaining that. It's got its own unique UX elements and it's possible to make this software work for your needs, too. But it won't be a replacement as in "drop in".

**Comment by probonopd** [comment]
Someone comes along and sees my software, then makes some new other thing that addresses the same or a similar need. Fine with me. But then if someone starts talking down my software to promote some new other thing, while this new other thing does not do what my software does (= just work for me), then someone can't expect me to use, test, or promote that some new other thing. Let alone deprecate it. I hope this is not unreasonable but this is my firm position. After all, this is a fun hobby project for me.
