### ISSUE TITLE
The tools update and remove inside the AILL AppImage do not find their Qt

### ISSUE THREAD

**Issue by probonopd** [TheAssassin/AppImageLauncher#179]
The tools update and remove inside the AILL AppImage do not find their Qt.

**Comment by TheAssassin** [comment]
Good catch. AIL Lite is in public beta right now, I haven't got to testing it myself on a variety of other systems yet.

There's two ways to solve this. One is to extend linuxdeploy in some way to allow for additional binary dirs (by default it only deploys preexisting stuff in `AppDir/usr/bin`, this would allow other such directories e.g. as an env var, wouldn't be overly hard to implement since all paths are already calculated and not just guessed by liblinuxdeploy). Alternatively, we could just add `-e .../[update,remove]` and have linuxdeploy put them into `AppDir/usr/bin` and call them from there. That's much easier to do and also faster.

I am in favor of the first option in general, but as a quick fix will probably go for the second to get this fixed ASAP.

**Comment by TheAssassin** [comment]
@probonopd please check whether 1e35986 fixes the issue.

**Comment by probonopd** [comment]
I would love to, but the build failed: https://travis-ci.org/TheAssassin/AppImageLauncher/builds/553302966

**Comment by probonopd** [comment]
> There's two ways to solve this. One is to extend linuxdeploy in some way 

`linuxdeployqt` has `-executable` where you can specify additional binaries the dependencies of which should be deployed (and rpath of the binaries and dependencies is rewritten) but more and more I would find it better if all pre-existing binary executables anywhere inside the AppDir would automatically undergo "treatment".

**Comment by TheAssassin** [comment]
I don't like the idea of having random binaries fly around in an AppDir. I forgot to push the fix, the build failed anyway though due to issues @ Docker Hub.

**Comment by probonopd** [comment]
> I don't like the idea of having random binaries fly around in an AppDir

I don't quite understand - `update` and `remove` are already "flying around" in the AppDir?

**Comment by TheAssassin** [comment]
Yes. Hence the option to add additional binary dirs. We could also add some CLI option(s).

The point is, I don't want to auto-deploy any random binary. That'll just add bloat, these binaries might never be called.

**Comment by probonopd** [comment]
Then they should not be in the AppDir? Isn't it reasonable to mandate that everything in the AppDir should be deployed so that it works? Otherwise the AppDir may contain stuff that has no chance of working. I would take the position that any executables that shall not be deployed should not be in the AppDir in the first place.

My general philosophy is that it needs to "just work" without people having to take additional steps, read docs (no one does), etc.

**Comment by TheAssassin** [comment]
Issue's fixed. Closing. Discussion may continue in linuxdeploy's tracker, if needed.

**Comment by probonopd** [comment]
Confirmed, works for me. Thanks :+1:
