### ISSUE TITLE
Version 2 lite on Ubuntu 19.10 no such file or directory"

### ISSUE THREAD

**Issue by AndKe** [TheAssassin/AppImageLauncher#253]
```
$ ./appimagelauncher-lite-2.0.0-travis866-4075ba1-x86_64.AppImage install
Installing AppImageLauncher Lite
Created symlink /home/andre/.config/systemd/user/default.target.wants/appimagelauncherd.service → /home/andre/.local/lib/appimagelauncher-lite/systemd/appimagelauncherd.service.
install: cannot create regular file '/home/andre/.local/share/icons/hicolor/scalable/apps/AppImageLauncher-Lite.svg': No such file or directory
```
"scalable" and the rest of /scalable/apps/AppImageLauncher-Lite.svg does not exist.

**Comment by TheAssassin** [comment]
These shell script installers can be buggy. I've attempted to fix the issue in the latest build. Please try the `continuous` release. If it works for you, we can make another release.

**Comment by AndKe** [comment]
As you see it worked much better now:
```
./appimagelauncher-lite-2.0.2-travis879-29526eb-x86_64.AppImage uninstall
Uninstalling AppImageLauncher Lite
Removed /home/andre/.config/systemd/user/default.target.wants/appimagelauncherd.service.
Removed /home/andre/.config/systemd/user/appimagelauncherd.service.
rm: cannot remove '/home/andre/.local/share/icons/hicolor/scalable/apps/AppImageLauncher-Lite.svg': No such file or directory
andre@loke:~/Downloads$ ./appimagelauncher-lite-2.0.2-travis879-29526eb-x86_64.AppImage install
Installing AppImageLauncher Lite
Created symlink /home/andre/.config/systemd/user/default.target.wants/appimagelauncherd.service → /home/andre/.local/lib/appimagelauncher-lite/systemd/appimagelauncherd.service.
Error in file "/home/andre/.local/share/applications/Slic3r.desktop": "" is an invalid MIME type ("" does not contain a subtype)
Could not parse file "/home/andre/.local/share/applications/Arduino1.8.7.desktop": No such file or directory
Error in file "/home/andre/.local/share/applications/MissionPlanner.desktop": "" is an invalid MIME type ("" does not contain a subtype)
Error in file "/home/andre/.local/share/applications/MissionPlannerBeta.desktop": "" is an invalid MIME type ("" does not contain a subtype)
Error in file "/home/andre/.local/share/applications/MAKstripe.desktop": "" is an invalid MIME type ("" does not contain a subtype)
Error in file "/home/andre/.local/share/applications/u-Center.desktop": "" is an invalid MIME type ("" does not contain a subtype)
AppImageLauncher Lite has been installed successfully.
andre@loke:~/Downloads$ 

```
After launching FreeCAD_0.19-18522-Linux-Conda_Py3Qt5_glibc2.12-x86_64.AppImage
it created "appimagekit_6f6043878437a03b16cff404a1ac233c-FreeCAD_Conda.desktop"

Naming it FreeCAD Conda (I would say FreeCAD 0.19 would be more informative)

There is some complaining about MIME in other .desktop files, 

It did work, but no icon is displayed:
```
[Desktop Entry]
Version=1.0
Name=FreeCAD Conda
Exec=/home/andre/Applications/FreeCAD
Icon=appimagekit_6f6043878437a03b16cff404a1ac233c_freecad_conda
Type=Application
Categories=Engineering;
Comment=Feature based Parametric Modeler
Terminal=false
StartupNotify=true
NoDisplay=false
MimeType=application/x-extension-fcstd;
```

**Comment by TheAssassin** [comment]
The naming is up to the creator of the AppImage, we just use what we get presented. Please file issues at the original repository or get in touch with the authors otherwise.

The naming of the file is also intentionally done like this, the files are autogenerated and may be overwritten at any time. You can edit them, but these changes won't be persistent.

This issue is resolved, as far as I can see.

**Comment by AndKe** [comment]
resolved. 
Just a quick question; how is the icon supposed to work ?

**Comment by TheAssassin** [comment]
There should be a file `~/.local/share/icons/hicolor/*/appimagekit_6f6043878437a03b16cff404a1ac233c_freecad_conda*`. Some DEs are slow at updating this stuff, e.g., KDE. Since you haven't posted what DE you use, I can't tell for sure. As long as that file exists, things *should* be set up correctly.

Your AppImage might as well be buggy. You can check it with https://github.com/TheAssassin/appimagelint, which'll check desktop files and icons for validity.
