### ISSUE TITLE
Does it installs AppImage support in a OS which doesn't haves it?

### ISSUE THREAD

**Issue by DaniellMesquita** [TheAssassin/AppImageLauncher#277]
For example, unlike Ubuntu, AntiX doesn't comes with support for AppImage.

**Comment by TheAssassin** [comment]
Yes, of course!

AppImageLauncher is pretty much independent from distributions as long as they provide systemd and the required libraries. You could build AppImageLauncher yourself. Or, even better, try to make the maintainers of your distribution package AppImageLauncher.

Since your specific question has been answered, I consider this issue resolved. Please feel free to ask more questions in this or new issues.

**Comment by DaniellMesquita** [comment]
AppImage shouldn't depend on systemd, which makes it unusable in distros like Gentoo.
