### ISSUE TITLE
Failed to register AppImage in AppImageLauncherFS: could not open map file

### ISSUE THREAD

**Issue by Woobieman29** [TheAssassin/AppImageLauncher#286]
On my KDE Neon machine I used the configuration file to change the location of where appimages are stored to ~/AppImages. Works fine for awhile, and then on a couple of occasions I have gotten an error when launching an appimage stating "Failed to register AppImage in AppImageLauncherFS: could not open map file". When I went looking for the Appimage, I found that it had been moved into the original ~/Applications directory. Looking at the Appimagelauncher.cfg file, I see that it had been modified on 1/5, and that the location is now commented out. Here is the contents of the file:

`[AppImageLauncher]`
`#` destination = ~/Appimages
`#` enable_daemon = true

Perhaps this is being done by an update?

**Comment by HackettHsu** [comment]
I'm facing the same issue, too.
My system is *Debian-Kali* and my AppImage Software is *PicGo(2.1.2)*.
Before I use AppImageLauncher to open it, I tried to open it through the normal way like this: 
```bash
$ chmod a+x PicGo.AppImage
$ ./PicGo.AppImage
```
And the shell told me to open it with *--no-sandbox* command.
Perhaps this is the problem?

**Comment by hornetster** [comment]
Same prob here, but have done nothing. Was working fine for several days (have only just installed) then get this error.
Tried to reinstall, but same prob.

**Comment by TheAssassin** [comment]
@HackettHsu are you running as root? That isn't really supported as of yet, as systemd doesn't support root-but-user-level daemons. Also I wonder where you use that flag. Please open a new issue.

@hornetster please post more information about your system and which version you use (and where you got it).

@Woobieman29 I don't see how recent updates could've broken your installation. But it's not impossible. What version are you using right now? Do you recall which version was working fine last time (that'd help me limit the number of commits involved in this bug)?

Generally, this error indicates an issue with AppImageLauncherFS.

**Comment by aksh1618** [comment]
Faced the same issue on fresh install on Arch Linux (appimagelauncher-git) with KDE Plasma. The appimage is successfully copied, but this appears on selecting `integrate and run`:

![image](https://user-images.githubusercontent.com/26065812/74106477-5c588b00-4b8d-11ea-8016-0a1f6cab3059.png)

**Comment by TheAssassin** [comment]
As mentioned in #293, trying AppImageLauncher on a Raspberry Pi with Raspbian pointed me to the potential cause of this issue.

The problem seems to be that the appimagelauncherfs process is not running, but the integration dialog doesn't validate that. Instead, it just writes to a *regular* file called `register`. That may work fine. However, since the FS is not running, there is no `map` file, which therefore cannot be opened and creates this error message.

A reboot can fix that problem, as then appimagelauncherfs is usually started fine, and as the mountpoint is a temporary directory, it is also set up from scratch on boot.

So what we need here is better detection of the filesystem process is running. That'll produce *at least* a better and more helpful error message. Then, we can continue to dig for more issues, and ideally can remove the need to reboot again.

**Comment by Thatoo** [comment]
Hello,

I face this issue time to time. When I start my debian buster, it might work well or not. If not, I need to reboot and hope for a better chance.

`sudo systemctl --user status appimagelauncherfs`
is saying
`Failed to connect to bus`

and same if I try to restart.

**Comment by probonopd** [comment]
Another instance of this has been reported at https://discourse.appimage.org/t/unable-to-run-appimage-in-ubuntu-16-04/1763/3:

![image](https://user-images.githubusercontent.com/2480569/88897575-08c12300-d23b-11ea-80a2-3e561f2fb8d5.png)

Is there a solution we can point users to?

**Comment by TheAssassin** [comment]
Closing as obsolete. See #361 for more information.
