### ISSUE TITLE
Fix build system to not embed copies of appimagekit

### ISSUE THREAD

**Issue by shadeslayer** [TheAssassin/AppImageLauncher#29]
Hi
Would it be possible to fix the build system to not embed a source copy of appimagekit in order for this source to be included in Debian?

**Comment by TheAssassin** [comment]
@shadeslayer would it suffice to implement this as an optional CMake option?

The point of including these sources is that AppImageKit is pulled in as a submodule. When using the source tarballs, these sources can't be auto fetched, as the source tarball should not contain a copy of the Git repository. In AppImageKit, most dependencies are pulled in via CMake's external project feature, which works independently from Git (to be fair, it uses Git to clone a few dependencies, but that's a different story).

I would just introduce some kind of functionality to use e.g., `find_library()` to use an existing libappimage  `.so` file instead of building it.

**Comment by shadeslayer** [comment]
That is indeed how it should be done. You should check for the existence of AppImageKit headers using find_package and then use those using include_directories in CMake.

The git submodule fetching should be a fallback when it can't find AppImageKit in the system path.

**Comment by TheAssassin** [comment]
I just thought, we build our own runtime to run AppImages, which can't be built without the sources.
We must find a solution for this before excluding the AppImageKit sources.

If you write Debian packaging files, I'd consider using them for setting up a package repository as described in #21.

**Comment by shadeslayer** [comment]
Just so that we're on the same page, you want packaging for AppImageKit ?

**Comment by TheAssassin** [comment]
I did consider maintaining a package repository in order to improve the usability of the tool, esp. to make it easier for users to update the application in this phase. However, I wasn't very interested in setting up a Debian source package, and I don't know very much about RPMs. Therefore, I decided, if at some day, somebody writes source packages, I'd consider setting up builds on OBS.

**Comment by shadeslayer** [comment]
That doesn't really answer my question :D

**Comment by TheAssassin** [comment]
Ah, you said AppImageKit. Sorry, I was reading AppImageLauncher. As usual, I'm working on 3 projects at the same time.

Well, I doubt that @probonopd is really interested in it. The problem with AppImageKit is that it's a quite monolithic project. At the moment, a lot of different software projects are contained: the runtime, appimagetool, appimaged, and a couple of helper tools.

For this project, we'd need to have packages for two libraries it depends on: libappimageupdate (and libappimageupdate-qt, although that name should probably be changed at some time) and libappimage. libappimageupdate shouldn't be an issue, the project is modularized quite well, its main dependency (libzsync2) is a separate project, and we could link to an external library instead of building it ourselves as well. libappimage however would need to be built from an AppImageKit source package.

As mentioned before, for AppImageLauncher a custom runtime is required which I bundle in `/usr/lib/appimagelauncher/` at the moment. This runtime needs to be built from AppImageKit's sources as well.

Perhaps, in order to allow packaging of all these components, we should modularize AppImageKit and split it into its components. We should extract the runtime (which then could be built and distributed independently). For appimaged, this is discussed in https://github.com/AppImage/AppImageKit/issues/656, and I have some time left today, so I could perform the extraction today. I don't expect any major problems.

**Comment by TheAssassin** [comment]
```
Current version is an untagged development version, can only check for stable updates
```

How can I call the updater from the UI? Is there a parameter I can use to force a manual update?

**Comment by shadeslayer** [comment]
Oh meh, sounds like a non trivial task and I'll have to build the debs locally I suppose.

**Comment by TheAssassin** [comment]
@shadeslayer we could discuss replacing the current method. E.g., similar to the type 1 AppImages, I could try to extract the runtime part from type 2 AppImages (we don't need to copy the entire file in this case), patch it and run the AppImage with it. @probonopd would probably prefer this way as well.

**Comment by shadeslayer** [comment]
I'd prefer that the time gets invested into splitting everything properly for future inclusion in Debian as opposed to writing more workarounds which are most likely not going to be accepted in Debian.

**Comment by TheAssassin** [comment]
@shadeslayer the extraction of the runtime I mentioned would eventually remove the dependency on the AppImageKit code, i.e., we would not build a runtime any more, and could link to an externally provided libappimage.

**Comment by TheAssassin** [comment]
@shadeslayer I'll first finish the extraction of appimaged, then will refactor the AppImage run code to no longer use an external runtime.

See #31

**Comment by shadeslayer** [comment]
Ah, looks good.

**Comment by TheAssassin** [comment]
I created a prototype quality implementation of the proposed changes for the type 2 runner in #35. As mentioned there, we can't just merge it, though.

The problem is that without the "known good" runtime that we have at the moment (of which we know that it supports the current method), AppImageLauncher wouldn't be able to run older AppImages (pre-end-of-March-2018), which is a no go. We could probably implement the same workflow as for type 1 AppImages, but it is so inefficient I'm totally reluctant to implementing this for type 2 AppImages as well. I'm already reluctant to the method in #35 as it involves creating temporary files for every AppImage that is ever run.

I think in order to run type 2 AppImages efficiently and not bloat users' temp dirs, we need to continue to ship a suitable runtime. And I think the only viable solution is that, similar to appimaged, we need to extract the runtime from AppImageKit into a separate repository, and create a suitable CMake build infrastructure for it that'd allow us to link to the system libraries instead of shipping our own. Then, we could bundle this in an AppImageLauncher source package, without requiring the entire AppImageKit blob. And the packages could create a proper source package for AppImageKit, and create binary packages for libappimage and appimagetool.

CC @probonopd, you probably have a stake in this topic. I personally think it makes sense to develop the runtime indepentently from AppImageKit, as it is rarely ever changed, and could perfectly be pulled in by AppImageKit as e.g., a submodule, or an ExternalProject. And it'd allow us to thin out and improve AppImageKit's CMake infrastructure, making it more understandable for everyone.

**Comment by TheAssassin** [comment]
@shadeslayer sorry for the long waiting time. We've raised the priority of this again in the upstream project. 

The only viable way for us right now is to extract libappimage from AppImageKit. This allows us to add some flexibility for consuming applications like AppImageLauncher against which libraries we link. As we don't need any patches for libappimage in general, this will allow packagers to link against distribution provided squashfuse binaries etc.

Please see https://github.com/AppImage/AppImageKit/issues/840 for more information.

As soon as libappimage is in a state so that e.g., Debian could package it, you can start to package AppImageLauncher.

**Comment by azubieta** [comment]
Just to update things here, libappimage has been already extracted.
Now it's possible to only include the libappimage project and left away the rest of AppImageKit.

**Comment by TheAssassin** [comment]
No, that's definitely not the case. We still need the runtime and therefore use AppImageKit instead of libappimage.

**Comment by TheAssassin** [comment]
Update: https://github.com/TheAssassin/AppImageLauncherFS can eliminate the dependency to the runtime, and allows for using libappimage directly. It's just not stable enough yet so it could be shipped with AppImageLauncher.

**Comment by TheAssassin** [comment]
Dependency has been removed, AppImageLauncher now uses AppImageLauncherFS as a backend.
