### ISSUE TITLE
Is there any option to remove the suffixed version?

### ISSUE THREAD

**Issue by silvioprog** [TheAssassin/AppImageLauncher#292]
It would be nice an option to remove the suffixed version `(N.N.N)` from the shortcut name to show something just like `App-Name` instead of `App-Name (N.N.N)`.

**Comment by silvioprog** [comment]
Fixed by passing variable `VERSION=` before calling the `linuxdeploy` tool.

**Comment by TheAssassin** [comment]
That's ***not*** a solution. It's an antipattern! Please **always** embed version information in your AppImage. There's so many use cases in which this feature helps!

- multiple versions used in parallel
- distinguish between AppImage and system-wide installation
- ...

CC @probonopd

**Comment by silvioprog** [comment]
> Please always embed version information in your AppImage.

I would like to do that, but unfortunately I can't find a compliant alternative to avoid this below :confused: :

![image](https://user-images.githubusercontent.com/1456829/73447957-9bd9d880-433e-11ea-96b4-72469b60d925.png)

the `(257f71a)` in the shortcut name is useless in my case, because ...

> multiple versions used in parallel

... my application has a built-in upgrade control to avoid multiple versions in the same system.

> distinguish between AppImage and system-wide installation

My customers will receive only an AppImage binary, so a system installation isn't available at al.

IMO `linuxdeploy` should allow to remove the `(hash)` from the shortcut for those who doesn't want to show it for their customers.

**Comment by TheAssassin** [comment]
I see your problem, and I have to say I agree that this is a problem. Let me explain why that is embedded.

What you see there is the hash of the latest Git commit of your repository. For some reason appimagetool, the upstream tool that linuxdeploy-plugin-appimage uses to make the AppImage in the end, embeds that unless you explicitly override the value in the environment if there is a Git repo.
Personally I consider this not a version. See e.g., https://github.com/radareorg/cutter/issues/2037, why git hashes don't make for very good versioning.

CC @probonopd. We really should remove this Git hash automagic thingy.

Not embedding version information is annoying for your customers, too, though. How to differentiate between multiple versions of your AppImage? How to tell apart system and AppImage installation? The git hash at least provides a unique way of adressing AppImages in a menu. Might not seem relevant at a first glance but is when it comes to "name collisions". AppImageLauncher handles it by doing what a file browser would do when you copy a file and paste it again in the same directory, it appends `(2)` etc. But that's also not ideal.

Please consider versioning your tool. I know, it can be annoying, but it really adds value for your customers.

**Comment by silvioprog** [comment]
Thanks a lot for the detailed information! :+1: 

A suggestion: it could be a feature which enabled by default (as it already is), but providing an option allowing the programmer to disable it.

>> CC @probonopd. We really should remove this Git hash automagic thingy.

An option to remove this embedded info will be really very useful. All other application installed on many Linux distros doesn't show this info. In general, they shows their version at main window title and/or in an about dialog. I had never seen before a Linux application handling its version by embedding it on its shortcut name. 🤔

**Comment by TheAssassin** [comment]
Well, you kind of found "the option" already. The problem is that appimagetool *enforces* this git commit hash thingy, it *itself* attempts to *guessify* the "version". But git hashes are not version numbers, period.

**Comment by probonopd** [comment]
@silvioprog are you using any kind of versions?

When you make your AppImage, you can `export VERSION=1.0` before you call `appimagetool`, then `1.0` will be used for the version instead of the git hash.

You could also just use integers, count up 1 for each version you push out.

Then wou will not see the git hash.

(@TheAssassin I have moved to the build number for go-appimage instead of git hashes as the default, but users can always override `$VERSION`.)

**Comment by ThracianKnight1907** [comment]
Hello, has there been any progress on allowing users to remove the suffix from the desktop shortcut? Like instead of "App-name (1.3.5)" just "App-name"?

**Comment by probonopd** [comment]
Why would anyone want that @ThracianKnight1907? Especially since with AppImage, you can have many versions in parallel I think this is a really useful feature. Why would anyone not like this? Please help me understand.

**Comment by ThracianKnight1907** [comment]
Well, it would make Appimages feel more integrated with the system and help provide consistency with "regular apps" (installed from the distro's repo), which don't typically show their version. This feature would be useful in case the user only uses one version (the latest) of a given app, and/or wants to maximise consistency across the system.

**Comment by TheAssassin** [comment]
Again, I wouldn't consider *removing* those information a feature, but a step backwards. "Feeling more integrated" doesn't make a lot of sense. Applications installed with the traditional package managers could and probably should show their installed versions there, too, nowadays, as there's many other ways to install applications other than the good old package manager approach. With many file types (e.g., office documents), it's also important to launch them with the right version of a tool. The XDG desktop entry spec however doesn't support anything like "version information".

I also don't understand what it has to do with consistency. On all systems where AppImageLauncher is installed, the applications are always integrated like this. I'd call that very consistent.

The only cases which I consider annoying is when a Git hash is misused as a "version number". I've explained it a lot of times before, those don't qualify as version identifiers for many reasons, mainly because the user doesn't know how to identify which application is newer than another just from the hash. However, even those have a point. If multiple versions of an application are available, they help the user distinguish between similar-looking entries in the launcher.

**Comment by probonopd** [comment]
> consistency with "regular apps" (installed from the distro's repo)

I don't think we should water down AppImage capabilities to the (inferior) packaging systems of the past where you could have only one version of each application. Best get all your applications as AppImages, then it will feel consistent.

**Comment by ThracianKnight1907** [comment]
I was referring to AppImagelauncher, not Appimages in general. Like if there was a toggle in settings to remove the suffix and have them blend in with the rest of the system. Anyway, I now understand your point of view.
