### ISSUE TITLE
How can I temporarily disable the filesystem daemon?

### ISSUE THREAD

**Issue by xerus2000** [TheAssassin/AppImageLauncher#307]
**Is your feature request related to a problem? Please describe.**
I am currently developing an application that is distributed as an AppImage. For debugging, I am constantly rebuilding it and launching it via the command-line, but every time I have to deal with the appimagelauncher poppoing up. I would like to

**Describe the solution you'd like**
I would like to know whether and how I can temporarily disable the appimagelauncher daemon. I have tried simply killing the process from the task manager but it always respawns.

**Describe alternatives you've considered**
I can go into the settings and disable the daemon & integration question, but then I have to reenable it once I'm done.

**Comment by Xerus2000** [comment]
It gets even worse - when I rebuild the AppImage, I MUST terminate the appimagelauncherfs process (though it immediately restarts) to launch the updated version, otherwise it somehow keeps using the old version of the appimage...

**Comment by Xerus2000** [comment]
Now I just wanna get rid of the appimagelauncherfs process, but the wiki doesn't state how it isintegrated! - `service`? `systemctl`? I have no idea...

**Comment by Xerus2000** [comment]
Finally found it! `systemctl --user stop appimagelauncherfs`

But it still revives itself whenever I start an AppImage - what the heck?

**Comment by TheAssassin** [comment]
It is a mandatory service which you cannot just "shut down". It's required by AppImageLauncher. The only way to get rid of it is to uninstall appimagelauncher.

If you want to get rid of the desktop integration dialog, you need to declare your application properly as a terminal one by setting `Terminal=true` in your desktop file. Then, it won't trigger AppImageLauncher any more.

Regarding the "when I build a new version" problem, I'm not entirely sure why the old version would be launched. This should normally not happen. But thinking about it, I might have been affected by a similar issue lately. Can you please open a new issue?

**Comment by Xerus2000** [comment]
> If you want to get rid of the desktop integration dialog, you need to declare your application properly as a terminal one by setting `Terminal=true` in your desktop file. Then, it won't trigger AppImageLauncher any more.

There is no desktop-file, I am launching the appimage directly. It would suffice if I could somehow disable it till next restart or something.

**Comment by Xerus2000** [comment]
> Regarding the "when I build a new version" problem, I'm not entirely sure why the old version would be launched. This should normally not happen. But thinking about it, I might have been affected by a similar issue lately. Can you please open a new issue?

I am investigating, will open one...

**Comment by Xerus2000** [comment]
https://github.com/TheAssassin/AppImageLauncher/issues/308

**Comment by TheAssassin** [comment]
> There is no desktop-file, I am launching the appimage directly. It would suffice if I could somehow disable it till next restart or something.

I was referring to the AppImage's desktop file. Every AppImage contains one. If that AppImage doesn't declare an AppImage as being a terminal one, how could AppImageLauncher guess it shouldn't be triggered by it?

**Comment by Xerus2000** [comment]
So basically, the only way to completely prevent appimagelauncher from interfering is by uninstalling it? I still don't quite understand why I can't disable appimagelauncherfs temporarily?

**Comment by TheAssassin** [comment]
It is required to work around a bug in the AppImage specification. AppImageLauncher absolutely depends on it.

When an AppImage is run, the `binfmt_misc` integration (which is set up globally and cannot be disabled as needed) calls it through AppImageLauncher, which acts as an interpreter. However, AppImageLauncher needs to call the AppImage itself after having treated said AppImage. If AppImageLauncher attempted to directly call the AppImage again, `binfmt_misc` would be triggered again, leading to an infinite loop of AppImageLauncher windows. Therefore AppImageLauncher needs to call the AppImage in a special way. Normally, you could call `ld-linux.so.2` on the binary, but due to the bug in the AppImage specification I mentioned (which basically is a violation of the ELF specification), we cannot use this. Therefore we have to go a slightly less efficient and more complex route. AppImageLauncherFS is a FUSE filesystem which transparently removes the AppImage markers which would trigger `binfmt_misc`, so when you call an AppImage via the virtual FUSE file, it does not look any more like an AppImage.

This approach has been working *very* well for more than a year, and there's only few edge cases in which it breaks (mostly due to lack of experience with FUSE). It is improved continuously.

AppImageLauncherFS is a workaround that I would have liked to get rid of years ago, but you cannot simply change the existing AppImage specification.
The upcoming AppImage type 3 is going to fix the problem once and for all. Then, you don't need any such complex workarounds any more. AppImageLauncher and everyone else can simply call the AppImage directly with `ld-linux.so.2` and this way bypass `binfmt_misc`.

**Comment by airfield20** [comment]
This would be a nice feature to have whenever I am running an Appimage that is having compatibility issues with AppImageLauncher and I don't feel like dedicating time to working them out just to launch my app.

For now, I will temporarily uninstall to get my app running.

**Comment by TheAssassin** [comment]
@airfield20 is your issue perhaps related to #314? This electron updater stuff is incompatible with AppImageLauncher at the moment. The issue has been reported upstream, see https://github.com/electron-userland/electron-builder/issues/4046#issuecomment-582950434.

**Comment by TheAssassin** [comment]
Closing as obsolete. See #361 for more information.
