### ISSUE TITLE
Launching the same AppImage with different content leads to issues

### ISSUE THREAD

**Issue by xerus2000** [TheAssassin/AppImageLauncher#308]
I am building an AppImage file from source and launching it via commandline
- When I delete the file I have launched already and rebuild it with the same name but different code and launch that, it launches as if it still contained the old code
- After moving the AppImage, it executes with the new code correctly
- It also works after killing the appimagelauncherfs process

I once renamed the file and launched it and suddenly encountered this error, but I can't reproduce it right now:
```
Failed to register AppImage in AppImageLauncherFS: could not find virtual file for AppImage
```

AppImageLauncher version installed: ail-cli version 2.1.0 (git commit d1be7e7), built on 2019-12-01 00:44:00 UTC

**Comment by TheAssassin** [comment]
This is most likely due to these (and a few more) lines:

https://github.com/TheAssassin/AppImageLauncher/blob/7f53021adcd9da394ee2d83032e13cf163c17415/src/fusefs/fs.cpp#L478-L479

I think I have made a few too many assumptions while implementing the FUSE file system. I'll have to check how we can properly keep file descriptors for still-opened files while recognizing whether files have changed. I already have an idea how to implement that properly.

**Comment by TheAssassin** [comment]
Closing as obsolete. See #361 for more information.
