### ISSUE TITLE
Updater unavailable in PPA builds

### ISSUE THREAD

**Issue by salim-b** [TheAssassin/AppImageLauncher#330]
**Describe the bug**
I've installed AppImageLauncher through the official [PPA](https://code.launchpad.net/~appimagelauncher-team/+archive/ubuntu/stable) on Ubuntu 20.04 and it works so far, but the AppImageLauncher GUI says **`updater unavailable`** (under _Available Features_).

**Expected behavior**
I'd expect to see `updater available for AppImages supporting AppImageUpdate` instead.

**To Reproduce**
1. Install AppImageLauncher from the PPA:

   ```sh
   sudo add-apt-repository ppa:appimagelauncher-team/stable
   sudo apt install appimagelauncher
   ```

2. Run `AppImageLauncherSettings`

**Screenshots**

![screenshot](https://user-images.githubusercontent.com/20040931/81821759-c59bc180-9521-11ea-855e-d02f879cb167.png)

**System, software and AppImage information**

Ubuntu 20.04, GNOME 3.36.1

`AppImageLauncher version 2.1.3 (git commit 7408819), built on 2020-04-25 20:19:33 UTC` (latest `focal` version from PPA)

**Comment by TheAssassin** [comment]
@shoogle any idea why that is?

**Comment by ThxAndBye** [comment]
I'm having the same problem with the version from the ppa on PopOS 20.04 LTS.
![Screenshot from 2020-05-18 15-47-09](https://user-images.githubusercontent.com/16294365/82220514-08450b80-991f-11ea-8c80-c77ed3ebf9c7.png)

**Comment by TheAssassin** [comment]
PPA builds won't be able to use the updater until libappimageupdate is available. Sorry for the inconvenience. I'll update the README.

Perhaps we can offer something like what we had in appimaged: provide an option where you can point to an AppImageUpdate AppImage, and use that then to update. The built-in updater's core would be replaced by that, and the integration logic that comes after that could still be run.

**Comment by salim-b** [comment]
Do you know when ~ libappimageupdate will be available properly packaged for Debian? I can wait a while :)

> Perhaps we can offer something like what we had in appimaged: provide an option where you can point to an AppImageUpdate AppImage, and use that then to update. The built-in updater's core would be replaced by that, and the integration logic that comes after that could still be run.

If you wanna offer an alternative way to provide AppImageUpdate, I'd suggest the following: If AppImageLauncher can't resort to the built-in AppImageUpdate for whatever reason, it should look in its integration directory for an AppImageUpdate AppImage and use this if found. If not found, instead of just saying `updater unavailable` in the GUI, it could show a button to `install AppImageUpdate` which downloads and integrates the latest AppImageUpdate AppImage. That would be the most simple and "intuitive" UX I think.

**Comment by shoogle** [comment]
@TheAssassin 

> Edit: I think I know why. AppImageUpdate resp. libappimageupdate have not been packaged properly for Debian, so the PPA cannot offer it easily...

I had a look at this. It's certainly easiest if all dependencies are in Debian, but it's not strictly necessary because anything not in Debian can be built from source on Launchpad in the same way as AppImageLauncher is itself built from source.

The first step is to create a mirror of https://github.com/AppImage/AppImageUpdate on Launchpad. The next step is either to mention this mirror in the recipe for AppImageLauncher (i.e. build both at once) or to create a new recipe just for `libappimageupdate` (this would involve creating Debian packaging for it too since none exists already).

So it wouldn't be too difficult, except AppImageUpdate [has its own dependencies](https://github.com/AppImage/AppImageUpdate/tree/rewrite/lib) which are also not in Debian (and they have dependencies too), so these would also need to be mirrored on Lauchpad. Recipes always build against the latest commit, not a fixed commit like Git submodules, which can lead to problems if the dependencies change something since you last updated the submodules.

An easier way might be to setup a "mega" repository that expands all the submodule code. You wouldn't develop on this repository, but when you push a commit to the main repository it would trigger an update in the mega repository. Launchpad would just build all the code in the mega repository and not have to worry about fetching dependencies from elsewhere.

But perhaps the best solution of all is to ditch the PPA entirely and focus on providing AppImageLauncher itself as an AppImage. Is there a way we could self-integrate AppImageLauncher, including setting up the necessary `binfmt` hooks, maybe by running it as root?

**Comment by TheAssassin** [comment]
@shoogle there's a reason AppImageUpdate hasn't been packaged yet, you mention the same issues they've found. AppImageUpdate is pretty annoying to package. It needs to be fixed with regards to that, but I hardly have time for this project...

**Comment by qrkourier** [comment]
I am also trying to enable auto-updates for AppImages that I've integrated in the desktop by opening with AppImageLauncher. I have the same symptoms as @ThxAndBye on the same OS.

```bash
❯ cat /etc/lsb-release
DISTRIB_ID=Pop
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Pop!_OS 20.04 LTS"
```

**Comment by shoogle** [comment]
@TheAssassin 

> Perhaps we can offer something like what we had in appimaged: provide an option where you can point to an AppImageUpdate AppImage, and use that then to update.

How about you detect when the user tries to integrate the AppImageUpdate AppImage and then, in addition to asking whether to move it to ~/Applications, you also ask whether to use it for future updates?

**Comment by TheAssassin** [comment]
Detecting some AppImages and being sure they're the ones you think they are is just utterly unreliable. It'll be a significant amount of code that needs to be maintained. It's not worth it, from a maintainer's point of view. It's on your distro to package the dependencies. The PPA is pretty much a best-effort distribution, just like the packages you can find here on GitHub. I'll mark this issue as wontfix, as there's no good solution from this project's point of view.
