### ISSUE TITLE
Cant Update

### ISSUE THREAD

**Issue by IJR222** [TheAssassin/AppImageLauncher#346]
**Describe the bug**
I cannot update due to the apparent fact that it changed the name
Failed to check for updates:

Fetching latest release information from GitHub API
None of the artifacts matched the pattern in the update information. The pattern is most likely invalid, e.g., due to changes in the filenames of the AppImages. Please contact the author of the AppImage and ask them to revise the update information.
Fetching latest release information from GitHub API
None of the artifacts matched the pattern in the update information. The pattern is most likely invalid, e.g., due to changes in the filenames of the AppImages. Please contact the author of the AppImage and ask them to revise the update information.
ZSync URL not available. See previous messages for details.
**Expected behavior**
Update Properly

**To Reproduce**
1. Go to 'menu icon '
2. Right Click Application and update
3. See error

]

**System, software and AppImage information**
Your distribution and desktop environment (including version numbers): [manjaro kde 5.19.2]

AppImageLauncher version installed: [appimagelauncher 2.1.3-1]

**List of AppImages you tried:**
keepassxc 2.6.0

**Comment by TheAssassin** [comment]
Either the update information in the AppImage is broken and does not resolve to real files (happens a lot thanks to some annoying forced auto-detection of those information which would require the devs to also put additional files on their download pages; if they don't do it there's no good way from AppImageUpdate to detect this; it'd be better not to embed update information *at all*), i.e., the AppImage simply doesn't support updating and it's a false positive, there's been an error with KeePassXC's deployment and they simply forgot to put the `.zsync` files online, or there's a bug in AppImageUpdate. In all these cases, this is the wrong issue tracker. Please create an issue at https://github.com/keepassxreboot/keepassxc. If they confirm the bug is not on their end, please create an issue over at https://github.com/AppImage/AppImageUpdate.

**Comment by TheAssassin** [comment]
CC @probonopd -- this auto detection stuff creates these problems regularly. I'm still opposed to this kind of paternalism.

**Comment by probonopd** [comment]
> this auto detection stuff creates these problems regularly.

Do you have something specific that "auto detection stuff" is doing wrong here?

**Comment by TheAssassin** [comment]
Why embed update information if you cannot guarantee that the user who is "delighted" with the guessified information also uploads the `.zsync` files? That never made any sense from a UX perspective. AppImageUpdate cannot differentiate between "user did not upload the files on their GitHub release page, please ask them to do it", "user builds on Travis but does not use GitHub releases to distribute their AppImages" and "there's an actual error". All AppImageUpdate sees is "files missing despite update information available, cannot continue" and shows the above error message.

It would be better to only embed update information if the devs actually *want* to support AppImageUpdate. Right now, users of AppImageUpdate are lost with this error message. Why not simply tell users of Travis and GitHub "consider supporting AppImageUpdate" instead of paternalize them, guess some values that are not even known to work, embed those and risk this misleading error message?
