### ISSUE TITLE
AppImageLauncher is partially broken on Linux MInt 20 (Cinnamon)

### ISSUE THREAD

**Issue by grande-mephistopheles** [TheAssassin/AppImageLauncher#359]
**Describe the bug**
Not all of the features of AppImageLauncher is working in Linux Mint 20 Cinnamon

**Issues**

**Issue 1:** The appimages are integrated into the system alright, but the update feature is broken. I'm using the PPA for stable build. As far as I know it's a dependency bug that is not packaged in the newer ubuntu releases

**Issue 2:** The "Remove AppImage from your system" feature only works when accessing from the panel (screentshot 1). From the Cinnamon application menu it does not show up (screenshot 2). It may be a Cinnamon dependency, I'm not sure. 

**Note:** The "Uninstall" you see from the context menu is a feature of linux mint, an easy way to uninstall any app added via deb/repository. Unrelated to AppImageLauncher. Not all cinnamon distributions have this.

**Issue 3:** The launcher is not letting me update appimages that has built-in update feature. The appimage is showing update available but not updating (check scrennshot 3) . Even if I use the built-in update feature to update, it doesn't work (Standard Notes) -- even if I follow instructions according to screenshot 4 & 5, when I restart the app it comes back to screenshot 3. It may be unrelated to AppImageLauncher.

**Issue 4:** Icons for some appimages are blank (Joplin in this case)

**Screenshots**
![stn](https://user-images.githubusercontent.com/58479925/92937166-82ebe680-f43a-11ea-88c8-e35d02bb75cd.png)
![stn2](https://user-images.githubusercontent.com/58479925/92937177-867f6d80-f43a-11ea-9d56-b409c2cc7aa6.png)
![stn3](https://user-images.githubusercontent.com/58479925/92937717-39e86200-f43b-11ea-92ad-2e1d2fd6dc2a.png)
![stn4](https://user-images.githubusercontent.com/58479925/92954738-7c1d9d80-f453-11ea-8b70-f009bc583ebf.png)
![stn5](https://user-images.githubusercontent.com/58479925/92954741-7de76100-f453-11ea-8130-8f09110c99ed.png)

**System, software and AppImage information**
OS: Linux Mint 20 Cinnamon
Cinnamon version: 4.6.7
Linux kernel: 5.4.0-47-generic

AppImageLauncher version installed: 202004252016-stable-7408819~ubuntu20.04.1 ; (installed from PPA stable version: https://launchpad.net/~appimagelauncher-team/+archive/ubuntu/stable)

**List of AppImages you tried:**
- Standard Notes
- Joplin
- Subsurface

**Comment by grande-mephistopheles** [comment]
Update: Even after purging AppImageLauncher through apt, the services 'appimagelauncherd' and 'appimagelauncherfs' kept running on my system. I had to kill them manually to remove.

**Comment by grande-mephistopheles** [comment]
__Update 2:__
>Issue 4: Icons for some appimages are blank (Joplin in this case)

This is a prbolem with Joplin itself. Unrelated to AppImageLauncher

Currently, I'm using the `appimaged` daemon from https://github.com/AppImage/appimaged/releases/download/continuous/appimaged-x86_64.AppImage
This one does not interfere with the built-in update mechanism of appimages.

**Comment by TheAssassin** [comment]
This issue is quite annoying to work with for me. The screenshot have no numbers, but you reference them using some index scheme. Also, half of what you describe here could be found in existing issues. Please open separate issues for separate problems in the future. (The issue template even suggests that scheme (as it talks about "the bug", not "the bugs")).

I will answer to your questions, but I will close this issue as invalid.

> The appimages are integrated into the system alright, but the update feature is broken. I'm using the PPA for stable build.

It's well documented (in the README and *various* existing issues) that this feature *is not* and *will not* be available with PPA installations.

Broken is just wrong, it's simply unavailable!

> The "Remove AppImage from your system" feature only works when accessing from the panel (screentshot 1). From the Cinnamon application menu it does not show up (screenshot 2). It may be a Cinnamon dependency, I'm not sure.

Please ask your distribution or the Cinnamon folks about it. The feature is implemented following the XDG desktop entry standard and works just fine on any other desktop.

> The launcher is not letting me update appimages that has built-in update feature.

It looks like you got some Electron based ones. See https://github.com/electron-userland/electron-builder/issues/4046#issuecomment-631366463. This has been asked and replied more than once in this issue tracker.

> Icons for some appimages are blank (Joplin in this case)

As you figured out yourself, many AppImages are just broken with regards to that. Existing issues discuss this as well. You can help those projects by reporting issues and asking them to fix their icons. Check out https://github.com/TheAssassin/appimagelint, it provides feedback on the validity of icons.

**Comment by TheAssassin** [comment]
> Update: Even after purging AppImageLauncher through apt, the services 'appimagelauncherd' and 'appimagelauncherfs' kept running on my system. I had to kill them manually to remove.

The package suggests upon uninstallation (both in the terminal and the system notifications) that a reboot is required. One cannot just kill both services and expect things to work normally, as binfmt_misc cannot be reset properly on most systems. This is also documented in an existing issue.
