### ISSUE TITLE
Update PPA for Ubuntu 20.10

### ISSUE THREAD

**Issue by paidhi** [TheAssassin/AppImageLauncher#368]
Please update the PPA on Launchpad to also have a package for Ubuntu 20.10.
This would be great.

**Comment by TheAssassin** [comment]
@shoogle if you got a few, could you please take care of this?

**Comment by shoogle** [comment]
@TheAssassin, I've scheduled a build. Technically they were already active, but they failed because they used a version of Boost that isn't available in Ubuntu 20.10. I've told it to use a newer version of the library but we won't know whether it works until the build happens 8 hours from now. Not sure why Launchpad is running so slowly today.

**Comment by shoogle** [comment]
Looks like it was successful. Thanks @paidhi for pointing out it was missing before.

**Comment by TheAssassin** [comment]
Thanks @shoogle.
