### ISSUE TITLE
Use ~/Applications instead of ~/.bin

### ISSUE THREAD

**Issue by TheAssassin** [TheAssassin/AppImageLauncher#38]
CC @azubieta @probonopd

Instead of using a hidden, not-so-obvious directory for the integrated AppImages, I would like to change the directory and use the same one that @azubieta's [tool](https://github.com/azubieta/appimage-desktop-integration) uses.

I'd like to have some feedback before making any changes.

**Comment by TheAssassin** [comment]
As we learned in https://github.com/TheAssassin/AppImageLauncher/issues/33#issuecomment-389308971, users don't expect AppImages to end up in `~/.bin`, even if the integration dialog tells them so.

**Comment by azubieta** [comment]
Indeed they don't expect that. At the beginning we also put the
applications in a hidden folder but it was hard to find them there. Also
having the possibility of wipe them out by removing the file would be hard
if they don't know where the file is.

I also think that it would be great to include that folder in the
xdg-users-dir. So we could deal gracefully with translations.

El 16 may. 2018 10:15 AM, "TheAssassin" <notifications@github.com> escribió:

As we learned in #33 (comment)
<https://github.com/TheAssassin/AppImageLauncher/issues/33#issuecomment-389308971>,
users don't expect AppImages to end up in ~/.bin, even if the integration
dialog tells them so.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/TheAssassin/AppImageLauncher/issues/38#issuecomment-389556449>,
or mute the thread

**Comment by probonopd** [comment]
I agree that hiding the application from users is not a good idea, since it discourages them from using the file manager to copy the files (e.g., to a thumbdrive), or to delete them, etc.

Only thing to consider is that `$HOME/bin` is on the `$PATH` in some distributions by default (e.g., SUSE, openSUSE) whereas `$HOME/Applications` is not.

**Comment by TheAssassin** [comment]
@star-buck so, do you think a hidden directory is the way to go? We're actually discussing moving to a visible directory so that users don't need to enable hidden directories in their file browsers, making it a lot easier to find the integrated files again.

**Comment by probonopd** [comment]
I don't care about the name of the directory much, as long as it is not hidden from users. Unlike with e.g., Flatpak, the point of the "one app = one file" concept of AppImage is that the user can work with the application files directly.

**Comment by star-buck** [comment]
Hidden is better, otherwise just don't use "bin" when visible.

**Comment by TheAssassin** [comment]
Alright. Then I'd say we should use `~/Applications`. And I like @azubieta's suggestion to propose this directory in the Freedesktop standards.

**Comment by star-buck** [comment]
Any option is fine with me.

**Comment by star-buck** [comment]
is this released as binaries under "Releases"?

**Comment by GrayJack** [comment]
Can I change that via environment variables?

**Comment by TheAssassin** [comment]
You mean where the AppImages end up? No, but there's a config file `~/.config/appimagelauncher.cfg` that is created on first run. Just change `destination` to wherever you want to.

**Comment by GrayJack** [comment]
Thanks, that's what I was looking for :3

**Comment by probonopd** [comment]
> there's a config file ~/.config/appimagelauncher.cfg

Is it documented somewhere?

**Comment by TheAssassin** [comment]
Not yet. But I'm working on a configuration panel. Its documentation will probably be in the wiki, and on that page I'll also add details about the config file.
