### ISSUE TITLE
AppImageLauncher binfmt-bypass flagged as High Threat

### ISSUE THREAD

**Issue by dcendents** [TheAssassin/AppImageLauncher#380]
Hi,

I'm using Pleaxamp which is shipped as an AppImage and discovered this nice project and have been using it to easily add a desktop shortcut for Plexamp (on my work laptop).

AppImageLauncher raised a High severity alert and my IT department contacted me, here is the details, I hope it makes sense to you and if at all possible find a way to alleviate the problem.

```
SEVERITY: High
OBJECTIVE: Keep Access
TACTIC & TECHNIQUE: Defense Evasion via Process Hollowing
IOA NAME: ElfExecutedFromMemory
IOA DESCRIPTION: An ELF file was loaded and executed directly from memory, possibly to avoid detection. Check the process tree to determine if this activity was expected.
```
Process Tree:
* `/usr/bin/AppImageLauncher /home/user/Applications/Plexamp-3.3.1_f054308634d5b9c0ebe12e5533def0f6.AppImage --no-sandbox`
  * `/usr/lib/x86_64-linux-gnu/appimagelauncher/binfmt-bypass /home/user/Applications/Plexamp-3.3.1_f054308634d5b9c0ebe12e5533def0f6.AppImage --no-sandbox`
    * `/memfd:runtime (deleted)`

I think this happenend because I had Plexamp opened on my second screen and I clicked by mistake on the Plexamp icon on my main taskbar (because it is pinned as a favorite). I don't think AppImageLauncher was trying to do anything malicious, but if the agent running on my laptop think it is, there might be other apps that will flag this technique as well.

Just thought I'd let you know this technique is flagged as dangerous if you feel/can implement the feature in a different way.

Cheers

**Comment by TheAssassin** [comment]
Thank you. I wasn't aware I was implementing something malware-style. I also have hardly ever seen something like this alert system.

This alert describes the normal and expected behavior of the `binfmt_bypass` application. It will run that way whenever an AppImage is executed, there's no special workflow needed. Perhaps they can put it on the whitelist?

**Comment by dcendents** [comment]
They will not whitelist it, the IT department uses a commercial application and they assumes the threat detection list they pay for is accurate. Since this is not needed for work I cannot justify it either.

As I said my primary intention was simply to let you know, after that I will let you decide if/how you want to handle it, feel free to close the issue if this is not relevant.

My 2cents, and I have never developed this kind of system application. But my understanding from the report is that you load the application in memory and then lauch the process from memory. Maybe extracting the data on disk in a temporary folder and executing it from the disk would circumvent the problem, it seems the "load and execute from memory" is what is detected as a strategy used by malware to avoid detection.

**Comment by TheAssassin** [comment]
Well, I have no influence on questionable "security" software. Thanks for letting me know, though. I won't take any action, also because I don't know what to do. I'm certainly not going to sacrifice the gain in efficiency just because some scanner can't differentiate between legitimate and malicious software...
