### ISSUE TITLE
use fuse3?

### ISSUE THREAD

**Issue by jriddell** [TheAssassin/AppImageLauncher#394]
KDE has recently released kio-fuse which is cool and popular and uses fuse3.  fuse3 seems not to be quite compatible with fuse.  But cmake says appimagelauncher can only use fuse.  could it use fuse3 too?

**Comment by TheAssassin** [comment]
AppImageLauncher doesn't use FUSE internally any more. It used to require FUSE, but the FUSE filesystem was successfully replaced in release 2.2.0.

IIRC, libappimage uses squashfuse in order to be able to extract files from AppImages via libappimage. I wonder whether that's what pulls in FUSE? For the extraction itself, FUSE shouldn't be required.

That said, if FUSE 3 is needed, I think squashfuse will have to support it first.

**Comment by TheAssassin** [comment]
I think we can close this. AppImageLauncher itself doesn't use FUSE.
