### ISSUE TITLE
Warning on AppImage invocation: "libcurl.so.4: no version information available"

### ISSUE THREAD

**Issue by gwerbin** [TheAssassin/AppImageLauncher#403]
## Describe the bug

I see the following warning emitted on stderr when I start an "integrated" AppImage from the command line:
```
/usr/bin/AppImageLauncher: /usr/lib64/libcurl.so.4: no version information available (required by /usr/bin/../lib/x86_64-linux-gnu/appimagelauncher/libappimageupdate.so)
```

AppImages otherwise work as expected.

## Expected behavior

I expect to not see a warning.

## To Reproduce

1. Install Appimagelauncher & start the daemon with the Systemd service.
2. Integrate an Appimage.
3. Start the integrated Appimage from the command line.

## System, software and AppImage information

* OpenSUSE Tumbleweed, fully updated with `zypper dup` as of yesterday (Feb 211, 2021).
* Appimagelauncher version 2.2.0-travis995~0f91801 installed from [the published RPM](https://github.com/TheAssassin/AppImageLauncher/releases/download/v2.2.0/appimagelauncher-2.2.0-travis995.0f91801.x86_64.rpm).
* AppImage versions listed below.

## List of AppImages you tried

* [Neovim v0.5.0-dev+1102-g595f6e4d6](https://github.com/gwerbin/neovim/releases/download/nightly/nvim.appimage)
* [Via 1.3.1](https://github.com/the-via/releases/releases/download/v1.3.1/via-1.3.1-linux.AppImage)
* [Joplin 1.7.11](https://github.com/laurent22/joplin/releases/download/v1.7.11/Joplin-1.7.11.AppImage)

**Comment by TheAssassin** [comment]
The RPM packages are a best-effort approach. They are built on Ubuntu xenial currently. Once these builds are dropped, the builds will be moved to bionic (see #417 for more information). That might fix this issue.

On the other hand, as long as the tool works, I think we don't have to take immediate action. Let's keep the issue open, it might become an issue in the future. Also, the new bionic packages will have to be tested again.

**Comment by TheAssassin** [comment]
The warning is harmless, and can apparently not be solved with the way RPM packages are provided. Perhaps the upgrade to `bionic` will have some sort of effect, but no guarantees.

**Comment by rlad78** [comment]
So..I've encountered a situation where this breaks functionality of an AppImage. I am on openSUSE Tumbleweed as well.

I use the AppImage version of [Streamlink Twitch GUI](https://streamlink.github.io/streamlink-twitch-gui/) or STG for short. This makes use of [Streamlink](https://streamlink.github.io/index.html), which is a CLI utility. STG requires Streamlink >2.4.0, which is a problem for openSUSE as its repos only have up to 2.3.0. Luckily, Streamlink has an AppImage package for it's latest version. 

This is where we run into the main issue though. My configuration of STG was working fine until after I installed AppImageLauncher. After a bit of troubleshooting, I realized the issue listed here was the problem.

STG does a version check of Streamlink when it first starts, and running `streamlink.AppImage --version` gives it:
```sh
# ./streamlink.AppImage --version
/usr/bin/AppImageLauncher: /lib64/libcurl.so.4: no version information available (required by /usr/bin/../lib/x86_64-linux-gnu/appimagelauncher/libappimageupdate.so)
Icon theme "Papirus" not found.
Icon theme "Numix" not found.
streamlink 3.1.1
```
STG then cannot parse the output properly and throws an exception.

Given that I'm fairly new to AppImageLauncher, I'm not familiar with exactly how it works. Are there any current ways to blacklist an AppImage file so that AppImageLauncher will not try to interface with it? Or are there any ways to redirect the output of AppImageLauncher?
