### ISSUE TITLE
apt-key is deprecated.

### ISSUE THREAD

**Issue by tazihad** [TheAssassin/AppImageLauncher#428]
I am using Debian 11. It looks like Debian 11 is dropping conventional add-apt-repository. And adopting to something open-pgp key signature. Kindly change this to next release. Thank You.

```
sudo add-apt-repository ppa:appimagelauncher-team/stable
 Latest stable version of AppImageLauncher for all Ubuntu flavours.

AppImageLaucher is a helper program that makes it easier to organise and update AppImages on Linux. Learn more at https://github.com/TheAssassin/AppImageLauncher.
 More info: https://launchpad.net/~appimagelauncher-team/+archive/ubuntu/stable
Press [ENTER] to continue or ctrl-c to cancel adding it

gpg: keybox '/tmp/tmpn4osz2ph/pubring.gpg' created
gpg: /tmp/tmpn4osz2ph/trustdb.gpg: trustdb created
gpg: key 4AF9B16F75EF2FCA: public key "Launchpad PPA for AppImageLauncher Maintainers" imported
gpg: Total number processed: 1
gpg:               imported: 1
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
gpg: no valid OpenPGP data found.
```

**Comment by TheAssassin** [comment]
First of all, PPAs are for Ubuntu, not for Debian, they are not supported on Debian. I cannot provide PPA support for Debian users.

Second, what do you think we could do about our PPA? It looks like an issue within `add-apt-repository`, not like an issue of the PR. Suggestions welcome!

**Comment by tazihad** [comment]
Than can you provide flatpak support? will it be possible?

**Comment by TheAssassin** [comment]
No.

**Comment by mdrmike** [comment]
@TheAssassin The process to package PPA has changed, and this isn't a Debian specific error. 


It seems you may have missed the line in the error that reads:
`Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8))`



I don't actually use this project, and this issue just happened on my search results ... but thought I'd share in case this is news. This error will be encountered on latest versions of Ubuntu -- such as Ubuntu 21.04/21.10/22.04 -- (or Debian, Mint, PopOS!, ElementaryOS, Deepin, SteamOS, etc, which are all Debian based). Although the install may still work, `apt-key` is depreciated.



How to fix / More info:
- https://www.linuxuprising.com/2021/01/apt-key-is-deprecated-how-to-add.html
- or maybe https://askubuntu.com/questions/1295102/how-do-i-add-repo-gpg-keys-as-apt-key-is-deprecated

**Comment by TheAssassin** [comment]
Regarding Flatpak:

1) I doubt that this'll ever work, because of AppImageLauncher's requirements. It is a system software, and needs full access to many resources. I doubt Flatpak is suitable for it, and would allow it to work correctly.
2) Feel free to package it, but I will not:
  - provide any special support for this (I consider this downstream packaging, and I will send bugs your way first)
  - take part in the maintenance of the packaging (I don't like Flatpak and am not willing to learn how packaging works)
3) Please stop mentioning Flatpak in this issue, it's completely off topic. You can, however, open a new issue.

**Comment by TheAssassin** [comment]
@mdrmike you may notice that @tazihad said they use Debian 11 with an Ubuntu PPA. That makes little sense after all, and is an unsupported situation.

I'm relatively sure this is something that needs to be fixed in `software-properties-common`, which implements the `apt-key` command. I don't see how the repository needs to be changed. And even if so, Launchpad would likely take care of it automatically. None of the articles implies that *we* have to change anything. This is purely a client-side issue.

Therefore, closing, as this is nothing that could be fixed on the PPA's side.
