### ISSUE TITLE
Missing Support for Ubuntu 20 Focal Fossa

### ISSUE THREAD

**Issue by sgtcoder** [TheAssassin/AppImageLauncher#434]
**Is your feature request related to a problem? Please describe.**
Add support for Ubuntu 20 Focal Fossa

**Describe the solution you'd like**
Add support for Ubuntu 20 Focal Fossa

**Describe alternatives you've considered**
AppImage, but it's only "Lite". The Deb version can't install since Ubuntu 20 uses libcurl4 and not libcurl3

**Additional context**
N/A

**Comment by TheAssassin** [comment]
User totally ignored the README, and didn't fill in the template correctly.

**Comment by sgtcoder** [comment]
This is the template? I filled it out and followed it.

It still doesn't change the fact that there is missing support. What do you need me to add to your template?

**Comment by TheAssassin** [comment]
> The Deb version can't install since Ubuntu 20 uses libcurl4 and not libcurl3

Let's begin with the fact that there's _two_ `.deb` packages, so "the" is not helpful.

> What do you need me to add to your template?

How about the filename of the file you installed, the OS version, ... You should read https://www.chiark.greenend.org.uk/~sgtatham/bugs.html.

> It still doesn't change the fact that there is missing support.

Then, there's the compatibility table in the README: https://github.com/TheAssassin/AppImageLauncher#system-wide-installation

Since you want to force me to repeat the README text: install the bionic package, it is compatible. _I use it myself on a bionic machine._

Duplicate of:

- https://github.com/TheAssassin/AppImageLauncher/issues/383#issuecomment-751501554
- https://github.com/TheAssassin/AppImageLauncher/issues/375
- ...

**Comment by sgtcoder** [comment]
1. Thank you, the Bionic version of the Deb for Focal Fossa worked. Apparently I didn't try the Bionic version, just Xenial and the AppImage version.
2. I am still getting an issue when opening Todoist, but not sure if it's because of an issue with AppImageLauncher: "Todoist won't be able to log you in until you set up desktop integration for AppImage. Unless if there is something I am missing? https://todoist.com/help/articles/how-to-install-todoist-on-linux#appimage
3. I had looked at the compatibility chart and it didn't mention anything about Ubuntu 20. You should add Ubuntu 20 to the compatibility list, and that it uses Bionic Deb.

**Comment by TheAssassin** [comment]
> Ubuntu Bionic (18.04), Ubuntu Disco (19.04), Ubuntu Eoan (19.10) and newer

I find that relatively clear. I don't feel like listing every release since 18.04. 

>  Unless if there is something I am missing? https://todoist.com/help/articles/how-to-install-todoist-on-linux#appimage

You need to ask _them_. I don't know how their "detection" works. And I really have better things to do than run any sort of proprietary software to debug their hacks. Feel free to join the AppImage IRC channel and ask, but I have doubts anyone will be able to help you. https://docs.appimage.org/contact.html
