### ISSUE TITLE
Why delete appimage file on removal? LOTS of leftover files and connections after uninstall

### ISSUE THREAD

**Issue by auwsom** [TheAssassin/AppImageLauncher#456]
A couple of comments here.. I was looking for an appimage launcher like the PortableApps launcher that gave the option for automatic updates and had a nice menu to launch from plus a search, browse and install feature. I also installed AppImageD prior to this because it said it would update the AppImages. I had issued with a flood of messages when moving some appimage files to a partition with more space, see GH issue linked below. So I uninstalled AIL also. I also wanted to test if AIL would play nice with the "Portable Mode" of AppImages where by creating local dirs with the .config and .home endings, local to the appimages themselves, settings would be stored portably.

The problem is, now I have some appimages that are integrated, and some that aren't. So I reinstalled AIL to unintegrate them, and found out there is no way to do that without deleting the appimage file. 

I get that the file has been renamed, but deleting the entire file seems extreme. Is that necessary? I want to keep it. How about just un-random-stringing it? Also with the conflict with Appimaged below, it created a mass of files in the /tmp directory. I'm hoping that is where the settings file are sent to with this 'incognito' mode. You might consider adding the option to run in Portable Mode. 

I'm not sure what else AIL does beside somehow present .desktop like info like location and app icon to the OS launcher, but I'm hoping I can do that by pinning the portable appimage to taskbar. Is there some other functionality I'll be missing without AIL?

Also, I'm manually renaming the appimage files back to the name that matches the portable mode dirs. Most have worked, but Atom keeps recreating a dir in my home dir. I lost the random string so can't rename it back and try unintegrating with AIL. So there must be some other system pointer when I click the appimage file telling it to be integrated? Or else the portable mode isnt working with this app for some reason. I suppose I'll download a fresh file and see if it does the same. Maybe on at different system as well.. (fresh file does the same)

Yeah, so how do I unintegrate without deleting the appimage?

So, not super impressed with the uninstall process. Why is it the system has to be completely restarted? Also, I tried duplicating the appimage file before unintegrating with the right click context menu option "Remove from system..". After uninstalling AIL, it left that option in the context menu. Not clean.

Yep, still having more problems. When I pin an appimage to the taskbar, it cant find it next time because it's looking for a /tmp/.mount-blahblah file.

https://github.com/probonopd/go-appimage/issues/177

**Comment by auwsom** [comment]
Can explain briefly why binfmt is necessary to let the system know about the appimage files?

**Comment by auwsom** [comment]
I do see appimaged still trying to be called. I just removed a symlink to that in ~/Applications. And that it is the appimages creating the /tmp dirs. And that in them are the mounted volumes, and .desktop files and icon, so that I can just do this manually and still have Portable Mode working.

**Comment by TheAssassin** [comment]
Closing because I can't take anything useful (bug report, feature request, ...) from this mess of comments.

**Comment by ernstki** [comment]
> So, not super impressed with the uninstall process. Why is it the system has to be completely restarted? Also, I tried duplicating the appimage file before unintegrating with the right click context menu option "Remove from system..". After uninstalling AIL, it left that option in the context menu. Not clean.

@auwsom *I* understand what you're saying, but the maintainer is also not wrong about your GitHub-issue-tracker-question-asking skills needing some work here. You and me both, so no judgements. AppImageLauncher is a hobby project, written in someone's spare time, shared for free on the Internet, and they have no contractual obligation to make their hobby project work how anyone else thinks it should work. Keep this in mind next time.

I'm sure you've moved on with life, but for others arriving here after searching for "uninstall" in the issue tracker, the best answer I can come up with is that the `binfmt_misc` stuff is happening in kernel space, and rebooting is just the most reliable way to reset the kernel's brains back to the way they were before. The uninstall script used by AIL is [here](https://github.com/TheAssassin/AppImageLauncher/blob/master/resources/install-scripts/post-uninstall.in); you might be able to ask Copilot more questions about it. You can read more about the Linux kernel facility used [here](https://www.kernel.org/doc/html/latest/admin-guide/binfmt-misc.html).

I, too, had trouble getting on AIL's wavelength. After a while I tend to uninstall it and clean up the extra `.desktop` files and hashed `.AppImage`s by hand. I only use a couple of apps as AppImages, so I'm not getting the same benefits as someone who uses them a lot. It turns out [there are other ways](https://askubuntu.com/questions/1115321/extract-icon-from-appimage/1118922#1118922) to extract an icon from an AppImage for the purpose of making a desktop launcher, which is really all I was looking for.

At the same time, I think it's a brilliant solution for those who work with AppImages a lot. It also gave me the curiosity to go learn about `binfmt_misc` which I'd always wondered about with Java JAR files anyway, and I'm grateful for that!
