### ISSUE TITLE
Ubuntu - when app is updated it's removed from Dock/Favorites, new one is named (1)

### ISSUE THREAD

**Issue by timkgh** [TheAssassin/AppImageLauncher#463]
**Describe the bug**
Running AppImageLauncher on Ubuntu 21.10. Installed Bitwarden as AppImage. All was good until BW updated itself. Now the app shortcut that AppImageLauncher created is called `Bitwarden (1)` and the app got removed from the Dock/Favorites, had to manually edit the .desktop file and re-add the app to the Dock.

**Expected behavior**
The update should happen in place, not as a new app.

**To Reproduce**
See above

**System, software and AppImage information**
Ubuntu 21.10 default Gnome

AppImageLauncher version 202110042218-stable-0f91801~ubuntu21.10.1
libappimage0:amd64                         0.1.10+dfsg-0ubuntu1
Official PPA
deb http://ppa.launchpad.net/appimagelauncher-team/stable/ubuntu/ impish main

**Comment by TheAssassin** [comment]
This is a feature. Whenever two AppImages using the same name are integrated, they cannot be distinguished from each other in the launcher. By appending a numeric index, the entries can be identified by the user. It's at least better than having to guess which version you need to call. During updates, temporarily, two such entries are available until the old AppImage is gone. In order not to confuse the user, the old name is kept on purpose. Imagine updating one of two installed versions: when you have `App`,  `App (1)` upgrading `App` will lead to an entry `App (3)`. It's not ideal, but you can see something has changed there. Now converting `App (1)` to `App` and `App (2)` to `App (1)` (or the other way round) makes no sense to the user, they can not tell which one to call when they need a specific one.

The fact hat a numeric index is used is caused by Bitwarden failing to embed a version number in their AppImage. By setting `$VERSION` when running appimagetool, they could embed a usable version number. The version number would be appended before checking for collisions. When there is `App (1.0)`, upgrading to `App (2.0)` will not lead to such a collision, and appending numeric indexes is not required.
