### ISSUE TITLE
Remove `path` settings in desktop entry

### ISSUE THREAD

**Issue by ZhaoZuohong** [TheAssassin/AppImageLauncher#489]
### Pre-submit checks

- [X] I [checked for similar issues](https://github.com/TheAssassin/AppImageLauncher/issues?q=) beforehand, but could not find any, not even closed ones. I could not add my bug report to any existing issue.
- [X] I am going to take the time to to fill in all the required details. I know that the bug report will be dismissed otherwise.

### Describe the bug

Some desktop entries that shipped with AppImages include the `path` settings, which should not appear in the desktop entry generated by AppImageLauncher. For example, [OSU!Lazer](https://github.com/ppy/osu), specifies `Path=~` in its desktop entry, but it doesn't launch by auto-generated desktop entry created by AppImageLauncher. After deleting the `Path=~` line, osu launches fine.

### Expected behavior

If `path` appears in desktop entry shipped with an appimage, we should remove that line so that appimage will launch.

### Steps to reproduce the issue

1. Download an AppImage from [OSU!Lazer](https://github.com/ppy/osu)
2. Integrate it with AppImageLauncher
3. Run it from menu
4. Remove the line `Path=~` in generated desktop entry, and retry

### Distribution and desktop environment

Linux Mint 20.3

### Installed AppImageLauncher version

```
qt5ct: using qt5ct plugin
AppImageLauncher version 2.2.0 (git commit aa114f1), built on 2022-01-14 01:25:01 UTC
```

### List of AppImages you tried

* OSU! not working: [https://github.com/ppy/osu](https://github.com/ppy/osu)

**Comment by TheAssassin** [comment]
I'm not sure whether it makes sense to apply such a filter to all AppImages out there. @probonopd @azubieta

**Comment by probonopd** [comment]
> According to [Desktop Entry Specification](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html), Path means that "If entry is of type Application, the working directory to run the program in."

I don't think the AppImage tools implement `Path=`. It is just ignored.

**Comment by TheAssassin** [comment]
Nobody claims that it is implemented. That it's not is the issue (well, wouldn't call that "implemented", I guess "handled" makes more sense).

When a desktop file relies on `Path` to be set, the application won't run when run as an AppImage, because the working dir that should be set cannot be predicted reliably from the desktop file. Any workaround I can imagine is just a bad hack. The least appimagetool could do is warn about the use of `Path`. (No, I do not want to say it may not be included; there are valid use cases, e.g., running in `/tmp` or `/`, which the runtime won't interfere with).

**Comment by probonopd** [comment]
Well, `AppRun` is what is reading the `.desktop` file. It should be relatively straightforward to read the key and do a `chdir()` in `AppRun.c` to the location specified by `Path=` but prefixed with the mountpoint of the AppImage, but AppImages using their own versions of `AppRun` would need to have it implemented there. But then, shouldn't applications be written in a way that they run from _any_ location (e.g., by not using paths relative to `cwd`)?

**Comment by TheAssassin** [comment]
> Well, AppRun is what is reading the .desktop file.

Nobody uses `AppRun.c` any more because it introduces a variety of issues, and the few people who do should stop doing so.

>  It should be relatively straightforward to read the key and do a chdir() in AppRun.c to the location specified by Path= but prefixed with the directory that contains AppRun

This is guesswork. It may work. But you must never make such assumptions about other people's code. It is not safe to do so. I can easily give you a couple of valid application code examples where this will break, like for all kinds of workarounds. Only the application author (or packager) can be asked to make the decision whether such a call is going to make things work better, not worse. But then again, why bother doing it on the packaging side, when you have to touch the application code you can just fix the relative path issue in the first place.

Also, not what I was referring to, see below.

> but AppImages using their own versions of AppRun would need to have it implemented there.

Not the point. The issue is with *integrated* desktop files. The ones copied over from the AppImages to `~/.local/share/applications`. If one of these contains a `Path=` and the application relies on it to be set to, e.g., some resources directory, things will break. This is pretty much a "do not compile in hardcoded paths" issues. It does not have to be solved on the AppImage side, and this is not possible reliably anyway.

> But then, shouldn't applications be written in a way that they run from any location (e.g., by not using paths relative to cwd)?

Hence my proposal to at least warn about potential issues with such desktop files in appimagetool.

The existence of `AppRun.c` has led people to believe that just `chdir`ing into the AppImage mount point is a solution. It has never been anything but a workaround. Tools like linuxdeploy and its plugins try as hard as possible to avoid having to fall back on environment variables (not always possible), but they completely avoid the need for `chdir`ing to make some relative paths work.

Both `chdir` and changing environment variables stem largely from `AppRun.c`, which was a great help in the beginning of AppImage, but has subsequently been replaced more and more with solutions that do not change user-facing aspects of the process environment¹.

___________

¹ User-facing means the user sees a difference when running a specific AppImage. Let me give some examples:

- Changing `$LD_LIBRARY_PATH` to make the loader find and prefer libraries within the AppImage does make things work. The moment an application calls processes outside the scope of the AppImage, it will easily break, though. When the deployed application for instance wants to open the file browser or an image editor on a file using the appropriate helpers (e.g., `xdg-open`), these environment variables will be set on the new process as well. Unless the process cleans up the environment first (which requires business code within the application to be changed, and thus cannot be considered anything but a workaround to a limitation of the packaging approach), the system application will likely crash. Hence, it has been largely replaced with `DT_RUNPATH`-based deployment. There is no reason for it to be used any more. (Yes, I know, there is a variety of hacks to kind of "fix" the environment once the loader has done its job. Those are all workarounds, too, and they're not reliable. For instance, using an `$LD_PRELOAD`ed library hooking into some common functions (e.g., `open`) to do the job can break subsequent `dlopen` calls. Just do not use `$LD_LIBRARY_PATH`, period.)
- Already mentioned before, using some relative path magic to, e.g., make Gtk+ pixbuf loading work, requires a forceful `chdir` into the AppImage mount point. While this may not be a problem for some (especially GUI) tools, this cannot be assumed safely for any application, really. Consider this example: a tool is called and a relative path is passed to it. After changing the working directory, the relative path will not work any more. (And, no, you can't automagically fix that either with some heuristics, because you should never make assumptions about the semantics of path handling within someone else's code.)

**Comment by probonopd** [comment]
> The issue is with integrated desktop files. The ones copied over from the AppImages to ~/.local/share/applications. If one of these contains a `Path=`

My 2 cents: `Path=` should be removed when desktop files are integrated into the system, because the inside of an AppImage does not read such desktop files that are integrated into the system. So the only place where we _might_ considering doing something with `Path=` would be the desktop files _inside_ AppImages.

**Comment by TheAssassin** [comment]
> Actually the desktop environment might be what does the chdir when invoking the application specified in a desktop file that is integrated into the system.

Yes, that has been pointed two days ago by @ZhaoZuohong, see https://github.com/TheAssassin/AppImageLauncher/issues/489#issuecomment-1045896707.

> So as long as AppRun or anything else in the AppImage does not do a chdir, it should even work... Or am I wrong?

The culprit still is that one AppImage contained a broken value there. See the original post, where @ZhaoZuohong points out that removing `Path=~` from the desktop entry fixes the launch. I'm therefore relatively sure that that is something the folks from OSU! just forgot about when creating the AppImages.

Now one could automatically filter out all these values, but my point is that there are valid use cases of `Path`, and you cannot just assume safely that removing the values is acceptable. I'm strictly against adding some kind of heuristics to detect whether to remove the path or not (heuristics = statistics = there's a chance you're wrong, and we couldn't even enumerate this chance due to the lack of data).

Therefore, the easiest thing to do is to warn in appimagetool about such broken values.

This is not an AppImageLauncher issue, because it is not even a libappimage issue. This is an issue with OSU!Lazer, who ship a broken desktop entry. However, this *is* an AppImageKit issue, because appimagetool could at least issue a warning.

**Comment by probonopd** [comment]
Thanks for the clarification @TheAssassin which makes sense to me.

**Comment by TheAssassin** [comment]
It makes no sense to implement a filter there. We should simply warn people about it. Let's open issues in AppImageKit and appimagelint.
