### ISSUE TITLE
Install error on devuan

### ISSUE THREAD

**Issue by sulincix** [TheAssassin/AppImageLauncher#551]
### Pre-submit checks

- [X] I [checked for similar issues](https://github.com/TheAssassin/AppImageLauncher/issues?q=) beforehand, but could not find any, not even closed ones. I could not add my bug report to any existing issue.
- [X] I am going to take the time to to fill in all the required details. I know that the bug report will be dismissed otherwise.

### Describe the bug

```
+ systemctl restart systemd-binfmt
/var/lib/dpkg/info/appimagelauncher.postinst: line 25: systemctl: command not found
dpkg: error processing package appimagelauncher (--configure):
 installed appimagelauncher package post-installation script subprocess returned error exit status 127
```

### Expected behavior

-

### Distribution and desktop environment

-

### Installed AppImageLauncher version

-

**Comment by sulincix** [comment]
Devuan is systemd-free fork of debian. You must use **update-rc.d** command instead of **systemctl**

**Comment by TheAssassin** [comment]
Not really a bug, this is by design. I have no intention on writing my own service management for user-level daemons like appimagelauncherd. `systemd` makes managing such services extraordinarily easy by providing a `--user` feature.

Please feel free to open a feature request to support Devuan's init system.
