### ISSUE TITLE
stop looking in /Applications

### ISSUE THREAD

**Issue by jamcinnes2** [TheAssassin/AppImageLauncher#598]
### Pre-submit checks

- [X] I checked for similar issues beforehand, but could not find any. I could not add my proposal to any existing issue.
- [X] I am going to take the time to to fill in all the required details. I know that the bug report will be dismissed otherwise.

### Feature description

I keep getting journal/syslog messages like this every 30 seconds:
appimagelauncher-lite.AppImage[1234]: Directory /Applications does not exist, skipping

### Proposed solution

Do not spam syslog with these messages, or do not look for root folder '/Applications'

### Additional context

appimagelauncher is great thank you for making this.

**Comment by TheAssassin** [comment]
This is not a valid feature request because it describes a problem. This problem has been reported before, but I can't find a duplicate issue at this point. Please open a new bug issue and fill in all the required information like your AppImageLauncher version number. (I suspect the latest continuous release is not affected by this any more.)

**Comment by maribox** [comment]
> This is not a valid feature request because it describes a problem. This problem has been reported before, but I can't find a duplicate issue at this point. Please open a new bug issue and fill in all the required information like your AppImageLauncher version number. (I suspect the latest continuous release is not affected by this any more.)

You may have been looking for this: https://github.com/TheAssassin/AppImageLauncher/issues/432#issuecomment-1655036364
