### ISSUE TITLE
Arch: Appimage kit breaks build

### ISSUE THREAD

**Issue by NuLogicSystems** [TheAssassin/AppImageLauncher#60]
There are CFLAGS coming from the appimagekit submodules source codes dependancies.cmake file.
It's also downloading and trying building some libraries that are already available in Manjaro for some strange reason:
- xz
- inotify-tools
- libarchive
- GTest

Here the report from Manjaro, and what Philip did to fix it:
Report: https://forum.manjaro.org/t/appimagelauncher/52322/7
Commit:https://gitlab.manjaro.org/packages/community/appimagelauncher/commit/95fe74b3f4be8efc1eb13eb0fe003466e91022e7

I'm not normally against patches, but IMHO, that one is quite large, and shouldn't be needed.

**Comment by TheAssassin** [comment]
These `CFLAGS` must be externally provided. AppImageKit's CMake scripts do forward all CFLAGS set in the environment for cross compiling purposes (e.g., you can set it to `-m32` to cross-compile 32-bit builds).

Those CFLAGS must be set externally, and I am not entirely sure why this is the case. Anyway, it seems that the "embedding" of the CFLAGS in the build commands is the problem here.

Now, there's a few ways to work around this. The first one is to reduce the amount of external dependencies that are compiled oneself, and link to the system tools. There's a couple of options like `USE_SYSTEM_XZ=1` etc.

**Comment by NuLogicSystems** [comment]
Personally, I like option 2. ;)
However, I'll see what I can do as far as up voting those patches first thing Monday morning, or later tonight.

**Comment by philmmanjaro** [comment]
Well, it is a regression of: https://github.com/AppImage/AppImageKit/pull/823

**Comment by TheAssassin** [comment]
@philmmanjaro you're right, and I plan to investigate and fix that stuff properly next week.

**Comment by TheAssassin** [comment]
So, I wrote a simple `Findlibappimage.cmake` which works great, but we have a new problem. AppImageLauncher requires a custom built AppImage runtime to execute type 2 AppImages.

I have no idea how to get rid of AppImageKit for this dependency, and I've been thinking about this ever since I first implemented it that way. Suggestions welcome!

**Comment by TheAssassin** [comment]
https://github.com/AppImage/AppImageKit/pull/825 has been merged. @philmmanjaro can you check whether it works without the patch again?

**Comment by philmmanjaro** [comment]
@TheAssassin: yes, works again. Released as **1.0alpha+git20180724.cda3f6e-1**.

**Comment by TheAssassin** [comment]
Awesome! Please let us know if you have any further issues, normally they can be fixed quickly.
