### ISSUE TITLE
Configurable applications folder

### ISSUE THREAD

**Issue by dasBuero** [TheAssassin/AppImageLauncher#63]
It would be nice to have the ability to change the default installation folder (~/Applications) before installing or integrating AppImages (per app or as a default configuration for all apps).

Thank you for your effort so far, it is a very useful app!

**Comment by TheAssassin** [comment]
Thanks for your suggestion.

The directory `~/Applications` has been chosen because some other tools in and outside the AppImage ecosystem use it as well. Asking user to change this at the first start or something will likely break compatibility with these tools.

I'm open to implementing some config file which allows experienced users to change the path, though. Would that work for you?

**Comment by dasBuero** [comment]
> The directory ~/Applications has been chosen because some other tools in and outside the AppImage ecosystem use it as well. Asking user to change this at the first start or something will likely break compatibility with these tools.

I was not aware about this.

> I'm open to implementing some config file which allows experienced users to change the path, though. Would that work for you?

This should be a good solution. Thank you!

**Comment by TheAssassin** [comment]
Done! You can change the destination in `~/.config/appimagelauncher.cfg`.

**Comment by dasBuero** [comment]
Great! I will test it and report soon.

Thank you!
