### ISSUE TITLE
Doesn't show the image for OrcaSlicer_Linux_V2.1.1.AppImage

### ISSUE THREAD

**Issue by kwagnitz** [TheAssassin/AppImageLauncher#653]
### Pre-submit checks

- [X] I [checked for similar issues](https://github.com/TheAssassin/AppImageLauncher/issues?q=) beforehand, but could not find any, not even closed ones. I could not add my bug report to any existing issue.
- [X] I am going to take the time to to fill in all the required details. I know that the bug report will be dismissed otherwise.

### Describe the bug

Opening OrcaSlicer_Linux_V2.1.1.AppImage with  AppImageLauncher shows the gear icon.  The appimage shows an icon when listed in Nautilus.

### Expected behavior

I expected to see the correct icon for Orca on the dock.

### Steps to reproduce the issue

Double click on the Orca appimage in a nautilus window.  -Or run it with AppImageLauncher.

### Distribution and desktop environment

PRETTY_NAME="Ubuntu 24.04 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04 LTS (Noble Numbat)"
VERSION_CODENAME=noble

Kernel version Linux 6.8.0-39-generic

NVIDIA GeForce RTX™ 3060 Laptop GPU
X11 screen manager.
Gnome version 46

### Installed AppImageLauncher version

appimagelauncher_2.2.0-travis995.0f91801.bionic_amd64.deb

### List of AppImages you tried

arduino-ide_nightly-20240630_Linux_64bit.AppImage  -OK
Bambu_Studio_linux_ubuntu_v01.08.00.57-20231109141031.AppImage  -gear icon
Ondsel_ES_2024.2.0.37191-Linux-x86_64.AppImage  --OK

**Comment by TheAssassin** [comment]
Please provide a screenshot.

**Comment by kwagnitz** [comment]
![OrcaOnDock](https://github.com/user-attachments/assets/21363695-7add-40c2-9b22-47e07d070b52)
Screenshot of my dock with part of the Orca window showing.
The Orca icon is the gear at the bottom.

**Comment by TheAssassin** [comment]
> appimagelauncher_2.2.0-travis995.0f91801.bionic_amd64.deb

This is the _really_ ancient release. Please try the latest continuous build, it's stable, all that's missing for a release is packaging.

Apart from that, the OrcaSlicer desktop file is incorrect. They need to specify their `StartupWMClass` so that the window manager can associate the running program's windows with the pinned entry.

```
~> xprop WM_CLASS
WM_CLASS(STRING) = "orca-slicer", "OrcaSlicer"
```

Thus, the desktop file needs to be amended with either
```
StartupWMClass=orca-slicer

# alternatively
StartupWMClass=OrcaSlicer
```

References:

- https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html
- https://specifications.freedesktop.org/startup-notification-spec/startup-notification-0.1.txt

Thus, not a problem with AppImageLauncher nor with libappimage. Please let them know so they can fix it.

**Comment by kwagnitz** [comment]
After following the PPA instructions from the wiki for Ubuntu, I get:
The repository 'https://ppa.launchpadcontent.net/appimagelauncher-team/stable/ubuntu noble Release' does not have a Release file.
Updating from such a repository can't be done securely, and is therefore disabled by default.
