### ISSUE TITLE
Error: Failed to find integrated desktop file

### ISSUE THREAD

**Issue by charlbur** [TheAssassin/AppImageLauncher#98]
Hi,
My system is a Intel Celeron X86 64Bit Ubuntu 16.04 system. I installed the appimagelauncher_1-alpha-travis390.git20181021.d621fab_amd64.deb package successfully.
When I double click to launch a appimage the Desktop integration window pops up and asks if I want to integrate and run.  I select the "Integrate and Run" option and receive the above "failed to find integrated desktop file".
I am specifically trying to integrate Digikam 5.9.0 from the below Linux Appimagelinks.  It does seem to be doing the same thing with other apps as well.l
https://www.digikam.org/download/
https://download.kde.org/stable/digikam/digikam-5.9.0-01-x86-64.appimage

**Comment by njmckenzie** [comment]
Same issue here but with different AppImage ([cryptomator](https://bintray.com/cryptomator/cryptomator/download_file?file_path=cryptomator-1.4.0-x86_64.AppImage)).

**Comment by TheAssassin** [comment]
I can reproduce the issue with the latest Debian packages.

Can you please try to run the AppImage from the terminal, and check whether the two following messages are displayed:

```
AppImageLauncher error: appimage_shall_not_be_integrated() failed (returned -1)
AppImageLauncher error: appimage_is_terminal_app() failed (returned -1)
```

These messages would indicate the issue is within libappimage's desktop integration code. That code was rewritten recently by @azubieta, so a simple update might fix the issues. I'd just like to be sure whether you have the same error messages.

**Comment by njmckenzie** [comment]
@TheAssassin : Both of those messages were returned.

**Comment by azubieta** [comment]
Tried both AppImages directly in libappimage and everything worked as expected. @TheAssassin is AppImageLauncher being built using the latest libappimage ?

**Comment by TheAssassin** [comment]
@njmckenzie @charlbur we released new binaries, please retry.

**Comment by TheAssassin** [comment]
Tested, didn't fix the issue. AppImageKit needs to be updated to ship with the latest libappimage. I'll file a PR there, then will push another update here.

**Comment by njmckenzie** [comment]
> Tested, didn't fix the issue. AppImageKit needs to be updated to ship with the latest libappimage. I'll file a PR there, then will push another update here.

That's a bit weird. On my computer, the new release did resolve the issue.  I open Cryptomator and the desktop file is created, remove and update are in the right-click menu, and it no longer asks if I want to integrate and run it (all as I would expect the program to do).  So from my perspective, your fix worked.

The only oddity I still have is due to my menu editor (I think).  I am using KDE Plasma on Ubuntu 18.04.  The desktop file that appImageLauncher creates doesn't show up in the menu editor menus.  It is created in the same directory as all my other desktop files but the menu isn't picking up on it.  Trying to hunt down what attribute might be hiding it or what command to update the menu (applications-kmenuedit.menu).

**Comment by TheAssassin** [comment]
We've pushed another set of fixes for some edge cases. Please try again, and reopen if the issue persists.
